### ISSUE TITLE
Replace bulky sound-converter

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#1082]
There is a lot of old C code for the sound-converter used:
- Load all kinds of sound files via sndlib
- Convert sounds via resample 1.8.1

Especially the first is not required as we only have WAVE files of known format. A better solution than
- load from LST
- add header
- write to wav
- convert to wav
- load from wav
- write to LST

would be:
- load from LST
- convert in memory
- write to LST

For this I found a list of libraries which can do resampling: https://ccrma.stanford.edu/~jos/resample/Free_Resampling_Software.html

Especially appealing to me are:
- [smarc](http://audio-smarc.sourceforge.net/)
- [libsamplerate](https://github.com/erikd/libsamplerate) aka **S**ecret **R**abbit **C**ode

I'd try the latter which already has some CMake scripts (but needs patching though) and tests.
It should actually be added as a submodule to `s-c` but then we need recursive submodule init... Maybe add to main submodules?

**Comment by stefson** [comment]
Yeah, even though I never had issues with it the sound-converter binary is a bit of a bloaty. `libsamplerate` is a very popular lib, I'm using it since forever: it's neat, it's fast and lightweight. It is certainly highly appreciated if you added a possibility to use a system-libsamplerate lib for compiling against! :-)

**Comment by Flow86** [comment]
yea we could change that. The sound converter was only a kind of fallback solution, since the libsamplerate we had 2005 was not portable yet and likely to segfault under some circumstances. thats the reason we put it into a separate program.
The other reason was that each file had (as for opionion then) a different pitch/samplerate, so we had an easy program testing it out, but thats not necessary now anymore.

Please be free doing a on the fly conversion. But: should we write the resulting wav to disk at all? or we at least should simply write them as full qualified wav files, so we do not need to handle "is it converted?" at all

**Comment by Flow86** [comment]
(btw - SDL was not able to handle 9600khz wav files then - perhaps it can handle the samplerate conversion now itself?)

**Comment by Flamefire** [comment]
>The other reason was that each file had (as for opionion then) a different pitch/samplerate,

Well we still have 3 different samplerates. So we still need the scs file to tell us which samplerate is used where. I guess in S2 it was hard-coded in the binary...?

> should we write the resulting wav to disk at all? or we at least should simply write them as full qualified wav files

You are right this could be done on loading the sound resource. I started with a resource handling branch a while ago but couldn't figure out a good way to do the handling. How to include the meta-info in the loading process (e.g. for sounds, stiched together images (BOB, shadow...)), what to cache where and how to identify the resources. I guess the correct solution would be to have a descriptor file describing every resource, but this is so much work...   
And about storing: Is this even allowed legally? It certainly makes it easier: Convert once, then just use.

> (btw - SDL was not able to handle 9600khz wav files then - perhaps it can handle the samplerate conversion now itself?)

I tried it with proper 9.6kHz wavs and it didn't sound right. To loud and start/end was to abrupt. Didn't try SDL_mixer2 though.

**Comment by Flow86** [comment]
> I tried it with proper 9.6kHz wavs and it didn't sound right. To loud and start/end was to abrupt. Didn't try SDL_mixer2 though

I think these were the issues I had too

**Comment by stefson** [comment]
This seems to work pretty god out of the box. 

Do you still plan on allowing to build against a system libsamplerate? *_*

**Comment by Flamefire** [comment]
It would be possible but requires a custom Findlibsamplerate.cmake which probably should even use pkg-config and disable including the submodule if it is found. Without pkg-config it is impossible to know the version of libsamplerate and the author seems not to be willing to change this: https://github.com/erikd/libsamplerate/issues/70, so ensuring a minimum version is gonna be hard.

What would the advantage be over building the 4 c-files along with rttr?

**Comment by stefson** [comment]
It's highly discouraged by distros to fork libs from other sources and add them to a project, as this can cause licensing issues, and possibly issues related to *.so hell. Which is why I'm keen to use system boost and lua for compiling. For instance, `deadbeef` is the best audio player I ever used, but it's never going to be added to distros because of the internal forks they chose to use. 

Also it's about possible security issues as far as I understand it. Forking a lib creates a burden to maintain and fix possible sec. issues in the future, possibly on your own, or to leave it unfixed and thus removed by the distro's maintainer. 

Fun fact: right now, it's possible to compile the s25client binary from your branch without the need of having a system libsamplerate+dev available at all. Which means, that it links to it, even though it's not present!? :-)

**Comment by Flamefire** [comment]
> It's highly discouraged by distros to fork libs from other sources

I'm using the official repo. The lib is (should be) build statically, so no *.so hell.

I can add a find module though and possibly a setting like `RTTR_USE_SYSTEM_LIBSAMPLERATE` which makes the configure fail if none is found. What should the default be? Use the system or submodule one? @Flow86 ?

> Fun fact: right now, it's possible to compile the s25client binary from your branch without the need of having a system libsamplerate+dev available at all. Which means, that it links to it, even though it's not present!? :-)

As written in the PR a submodule is used. So no system module is required or used

**Comment by Flamefire** [comment]
@stefson: Try this: https://github.com/Return-To-The-Roots/s25client/pull/1083/commits/e3edc3539d6251d72ed6b0dae9f1c53915e40714 :)

**Comment by stefson** [comment]
Yeah, excellent! :) 

`-DRTTR_USE_SYSTEM_SAMPLERATE=OFF` is going to be the default?
