### ISSUE TITLE
Overriding graphics seems no longer to function

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1112]
After years I continued working on the babyolian scout. So I created a 8 graphic animation for left-top and wanted to test them. So I tried to replace the original roman graphics by creating a JOBS.BOB folder here `s25rttr_20190820\RTTR\LSTS\GAME\JOBS.BOB` Sadly those graphics seem not to replace the original graphics at all. So tried to unpack the following file: `s25rttr_20190820\RTTR\LSTS\GAME\Babylonier\JOBS.BOB.LST` and repalced the graphics in that folder.

There still seems to be no effect at all which is strange in two ways as I expected the second file to be in use.
The game says it loads the graphics but seems to not overwrite existing files anymore (or loads the jobs file after).

Has there been a change I missed on how to replace graphics or am I doing something wrong?

**Comment by Flamefire** [comment]
I have to double-check in which order exactly the stuff is loaded. It should be:

- S2 file
- LSTS
- LSTS/GAME
- <HOME>/LSTS

For babylonians I'm not sure as there is a hack to use the roman stuff somewhere.

What makes this even harder: The BOB files are more than just folders. They have this pasting-together of images and a link file. Could it be that the `JOBS.BOB.LST` is not used at all? It has a double-extension so it would try to replace `JOBS.BOB` instead of `JOBS` or so which won't work.

Can you provide some steps to test this? Best: the files to replace and a savegame to test

**Comment by Spikeone** [comment]
Steps I have taken:
1) Install RttR (ha, who guessed that?)
2) Copy the content of this zip:
[JOBS.BOB.zip](https://github.com/Return-To-The-Roots/s25client/files/3667319/JOBS.BOB.zip)
to `\RTTR\LSTS\GAME`
3) Remove this file `\RTTR\LSTS\GAME\Babylonier\JOBS.BOB.LST`
4) Copy the content of this zip:
[JOBS.BOB.LST.zip](https://github.com/Return-To-The-Roots/s25client/files/3667317/JOBS.BOB.LST.zip)
to `\RTTR\LSTS\GAME\Babylonier`

What do I expect now: When choosing the romans (JOBS folder) or Babylonian (JOBS.BOB.LST) folder and sending scouts on a road with left-up movement, the graphics should be changed.
![2019-09-29_14-29-26](https://user-images.githubusercontent.com/1276342/65832571-c4d15a80-e2c5-11e9-97b0-2210bd1d8e5f.png)
But simply nothing happens. I made videos where I replaced thos graphics but it has been some time since I did that.

Replay which shows roman and babylonian scouts with up-left movement
[2019-09-29_14-29-42.zip](https://github.com/Return-To-The-Roots/s25client/files/3667327/2019-09-29_14-29-42.zip)

**Comment by Flamefire** [comment]
I found the issue: We are using "archives", collections of items of any type. For "real" BOB files there is 1 item for the BOB file which is an archive itself. So when we try to load a BOB file we give it an archive, it then creates a BOB-type as an entry in that archive and fills that BOB-archive with the elements and more.    
Recreating this with a folder or an LST file is pretty much impossible because it fills the top-level archive (where the first entry is the BOB type) and not the bob type. But as the BOB-archive contains more info (e.g. the image links) it cannot be returned as a plain archive either

**Comment by Flow86** [comment]
we had a speciality in there when it was a bob file, it ignored that first item and went into the 2nd layer

**Comment by Flow86** [comment]
but it seems that it also can't load a bmp file from a directory (see #1235)

**Comment by Flamefire** [comment]
That's a different issue. Found it and can fix. Or are you working on libsiedler2 already?

**Comment by Flow86** [comment]
nope havent changed anything yet

**Comment by Flamefire** [comment]
The problem is the Loader::MergeArchives which does what it says on the tin: Recursively merge 2 archives. Here we have a "real" bob file which is an archive with 1 entry which is an archive and has bobtype "Bob". We want to override this but a folder is just an archive of files

I see 4 options to solve this:
1. Special case MergeArchives in case we have 1 entry which is a bobfile, then merge into that entry instead. Likely easiest but feels wrong and you can never overwrite the links (which I guess is never required)
2. Allow a subfolder in an extracted folder and put the images there which allows the merge to merge the correct thing. Problem: Cannot be done via lst files as they don't allow nested LST files (but they do allow BOB entries) and we have this in `data\RTTR\LSTS\GAME\Babylonier\JOBS.BOB.LST` but that should be removed (see discord)
3. Change the handling of loading a bobfile to make the "link" an archive-item (like palette animation) and hence load the images directly into the main archive. This allows full flexibility including overriding the links. The problem: To which index should the link list go? Usually all have a meaning already
4. Most work: Use proper loaders which load actual lists of textures. This means the loader would load the raw-bobfile, but stitch the images together and return a list of ready-to-use images already. Overriding is then simple as full images would be overwritten. I started on some infrastructure a while back but gave up as it is really hard without explicit resource descriptions and other reasons. Drawback would also be that you could not override the raw bobs (e.g. upper body parts)

**Comment by Flow86** [comment]
so conclusion:
- 1: simple special case inside the code to handle bob files differently
- 2: special case inside code for bob, rework of bob usage, special cases on disk, special case for lsts.
- 3: complex special cases inside code
- 4: most work, and not handling files the way before. still having the problem with the bobs handling

probably is 1. the easist way without having to much special cases and probably handle our use cases the fastest way

**Comment by Flamefire** [comment]
I wanted to address the design issue:
- Loading an LST populates the given archive, same as loading a folder
- If there is a BOB in an LST it will create an item which IS the bob, loading a folder with a BOB in it is not possible ATM
- Loading a BOB file adds entry to the archive which is the BOB, Loading a folder supposed to override a BOB will populate the archive directly

My proposal 2 would remove a shortcoming (see 2nd point). It is not really a special case for lsts as that would be untouched and we have a similar thing already: For fonts: They are archives (lsts) of archives (font)

Proposal 3 would address the third point above.

IMO Proposal 2 is the right thing to do and only requires override users to know to add a subfolder for bobs. Alternatively we could change the folder loading so to detect '*.bob' naming and mirror the structure of BOB archives so the subfolder won't be required. But then it becomes inconsistent if you want to override a bob file in a lst.   
Or last option: Loading `JOBS.BOB.LST` comes back as an archive named `jobs.bob` which the merger could (maybe) handle by checking for (still) existing extensions. But I actually don't want any extensions at that point for various reasons.
