### ISSUE TITLE
Typing a "%" in the chat crashes the game

### ISSUE THREAD

**Issue by Spacecpp** [Return-To-The-Roots/s25client#1143]
Title self-explanatory.
The console shows: 
```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::io::bad_format_string> >'
what<>: boost::bad_format_string: format-string is ill-formed
```

**Comment by Flamefire** [comment]
Which chat in particular does this apply to?

**Comment by Flamefire** [comment]
Ah I see, this is caused by our Log class. I'll change it so that the format string must be a string literal (`const char*`) so no custom string can be passed in. 

@Flow86 BTW: While convenient it might not be the best idea to mix the logging with formatting. E.g. I'm thinking about using libFmt instead of boost for formatting for more speed and because it is (basically) part of C++20. Changing that would require touching the log class again. Maybe it is better to have the log class just log and expected already formatted strings?
