### ISSUE TITLE
[Addon] Loot

### ISSUE THREAD

**Issue by Vinkdicator** [Return-To-The-Roots/s25client#1150]
I like the idea of finite resources such as iron, gold and stone but in this game they tend to be doomed to diminish rather than simply finite. When your soldier dies for example, the iron that went into his sword and shield disappears in a sense. As a partial 'fix' for this, I think it would be cool for soldiers and workers to drop their tools or weapons when they die. Higher rank soldiers could also drop gold. To collect them, you would just erect a flag at the spot then build a path to it, the carriers then carry it as normal. If soldiers die from a catapult, their items could be left at the door.

**Comment by Spikeone** [comment]
Well, thats one way to do it - but I don't think this really feels 'settlerish' as wares laying around simply is no mechanic (yet).
I'm a fan of adding more buildings to the game like the charburner which have higher food demands but produce finite resources. For example the water cleaner could get water from lakes instead of a well, iron might be found by crushing stones while gold might be mined in a deep gold mine.

That way the original buildings are simply faster and cheaper but you can still have a 'late' game. What about going that way rather than dropping items on the map?

**Comment by spacemanspiff2007** [comment]
I'd like the idea of replacement buildings which produce infinite resources.
Any plans of adding them?

**Comment by Spikeone** [comment]
should add them here: https://github.com/Return-To-The-Roots/s25client/issues/99

**Comment by Vinkdicator** [comment]
Mm, yes I understand that it is quite different to how settlers currently works. 
The reason I wouldn't want infinite buildings is because I like for the iron to remain finite, I just don't like the 'disappearing' aspect. I have suggested a building and worker idea in issue 99.

**Comment by Spikeone** [comment]
As we design everything (nearly) as an addon, you may not enable the "extra iron" building then (if we add such addon). On the other hand I can understand that disappearing seems wrong - but carriers just appearing in storehouses would be wrong then as well. Thats why I personally don't tend to think about what'd be logical, but good for the game (and feeling).
Thats why I like buildings morge :D

**Comment by Flamefire** [comment]
Yes something like this is not possible in S2 as there is no mechanic for wares laying at the ground and adding it would be to much IMO. So I'd rather say: Use the maps resources and if they really are out then it's a draw ;)

So I'd close this.
