### ISSUE TITLE
Most edges wrong on wasteland maps

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1182]
![image](https://user-images.githubusercontent.com/1276342/72664850-fe5bdc00-3a02-11ea-8c96-6e991bbbb692.png)

![image](https://user-images.githubusercontent.com/1276342/72664876-2ba88a00-3a03-11ea-922c-7347f10eebce.png)

![image](https://user-images.githubusercontent.com/1276342/72664882-3fec8700-3a03-11ea-9f82-a50a76f5b06f.png)

**Comment by Flamefire** [comment]
Can you try and fix those? It should be mostly straight forward: Edit RTTR\gamedata\world\wasteland.lua and fix up the `edgePriority`. Then you can use the hidden command `!reload` (enter in chat) to reload the gamedata which should instantly reflect the changes ingame. It won't be possible to add or change textures but about everything else should work including changing edges.

It WILL be difficult to come up with the correct order for the terrains and maybe it is impossible to actually rank them e.g. terrain A comes over B, B over C but C over A. This will be impossible as an order must be used. Otherwise we'd need a matrix (again) but then developing the gameData file will be very difficult. Possible alternative: For each terrain type list all terrain types over which an edge is drawn. As there are 22 terrain types you can imaging how much work this would be. Just check what you need. :)

**Comment by Spikeone** [comment]
```
90	Alpine Pasture	0x12
80	Lava Many		0x03
70	Mountain 		0x01	0x0B	0x0C	0x0D	0x22
60	Moor			0x05	0x06	0x13
50	Light Steppe	0x0E
40	Wasteland		0x04	0x07
30	Pasture 		0x00	0x08	0x09	0x0A	0x0F
20	Lava Few 		0x02
10	Lava			0x10	0x11	0x14	0x15	0x16

=> Problem: 	Mountain > Moor, Moor > Pasture, Pasture > Mountain
=> Idea: 		Moor > Pasture > Mountain

90	Alpine Pasture	0x12
80	Lava Many		0x03
70	Moor			0x05	0x06	0x13
60	Light Steppe	0x0E
50	Wasteland		0x04	0x07
x40	Pasture 		0x00	0x08	0x09	0x0A	0x0F
x30	Mountain 		0x01	0x0B	0x0C	0x0D	0x22
20	Lava Few 		0x02
10	Lava			0x10	0x11	0x14	0x15	0x16
```

So, we sadly have a circle which can't be fixed with the current system. I changed the arrangement which leads to wasteland/steppe draw over mountain which doesn't look so well but now it's still better.

[wasteland.zip](https://github.com/Return-To-The-Roots/s25client/files/4455719/wasteland.zip)
