### ISSUE TITLE
Credit skip doesn't work

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1236]
When you click, you don't skip a name but see the same again.

**Comment by Flow86** [comment]
I'm updating the credits and found the bug already. Will be fixed

**Comment by Flow86** [comment]
I will implement 
- Left-Click = forward
- Right-Click = back

**Comment by Flamefire** [comment]
Ok. I'll fix the graphic loading in the meantime. Just assume the current way of getting the images is working. 2 things that came to mind:
- There is a timer class which can be used instead of querying the videodriver. It has `getElapsed`
- The fade-in/fade-out could be done by the animation system. Just a need a new animation and start it at the right timepoint

BTW: The current "skipping" is a side effect of a bug :D
