### ISSUE TITLE
Override Bug: Skipping duplicate

### ISSUE THREAD

**Issue by Flow86** [Return-To-The-Roots/s25client#1247]
With the latest nightly I'll get this:

```
Skipping duplicate override file "D:\SIEDLER2\s25rttr-nightly\RTTR\LSTS\fonts.LST" for fontsLade ""D:\SIEDLER2\s25rttr-nightly\RTTR\LSTS\fonts.LST"": fertig in 14ms
...
Loading LST,LBM,BOB,IDX,BMP,TXT,GER,ENG,INI files from ""D:\SIEDLER2\s25rttr-nightly\RTTR\LSTS""
Skipping duplicate override file "D:\SIEDLER2\s25rttr-nightly\RTTR\LSTS\CREDITS.LST" for creditsLade Ordner "D:\SIEDLER2\s25rttr-nightly\RTTR\LSTS\CREDITS.LST"
  Lade "6" Einträge: fertig in 5ms
Skipping duplicate override file "D:\SIEDLER2\s25rttr-nightly\RTTR\LSTS\OUTLINE_FONTS.LST" for outline_fontsLade ""D:\SIEDLER2\s25rttr-nightly\RTTR\LSTS\OUTLINE_FONTS.LST"": fertig in 4ms
Skipping duplicate override file "D:\SIEDLER2\s25rttr-nightly\RTTR\LSTS\RTTR.LST" for rttrLade ""D:\SIEDLER2\s25rttr-nightly\RTTR\LSTS\RTTR.LST"": fertig in 1ms
Skipping duplicate override file "D:\SIEDLER2\s25rttr-nightly\RTTR\LSTS\firework.LST" for fireworkLade Ordner "D:\SIEDLER2\s25rttr-nightly\RTTR\LSTS\firework.LST"
  Lade "32" Einträge: fertig in 19ms
Skipping duplicate override file "D:\SIEDLER2\s25rttr-nightly\RTTR\LSTS\fonts.LST" for fontsSkipping duplicate override file "D:\SIEDLER2\s25rttr-nightly\RTTR\LSTS\io_new.LST" for io_newLade Ordner "D:\SIEDLER2\s25rttr-nightly\RTTR\LSTS\io_new.LST"
  Lade "14" Einträge: fertig in 7ms
Skipping duplicate override file "D:\SIEDLER2\s25rttr-nightly\RTTR\LSTS\logo.bmp" for logoLade ""D:\SIEDLER2\s25rttr-nightly\RTTR\LSTS\logo.bmp"": fertig in 0ms
Skipping duplicate override file "D:\SIEDLER2\s25rttr-nightly\RTTR\LSTS\menu.bmp" for menuLade ""D:\SIEDLER2\s25rttr-nightly\RTTR\LSTS\menu.bmp"": fertig in 13ms
Skipping duplicate override file "D:\SIEDLER2\s25rttr-nightly\RTTR\LSTS\CLIENT - Kopie.GER" for client - kopieLade ""D:\SIEDLER2\s25rttr-nightly\RTTR\LSTS\CLIENT - Kopie.GER"": fertig in 0ms
Skipping duplicate override file "D:\SIEDLER2\s25rttr-nightly\RTTR\LSTS\CLIENT.GER" for clientLade ""D:\SIEDLER2\s25rttr-nightly\RTTR\LSTS\CLIENT.GER"": fertig in 1ms
Skipping duplicate override file "D:\SIEDLER2\s25rttr-nightly\RTTR\LSTS\languages.ini" for languagesLade ""D:\SIEDLER2\s25rttr-nightly\RTTR\LSTS\languages.ini"": fertig in 1ms

```

- [X] there is a newline missing in one of the log messages
- [x] why does the "skipping duplicate override file" message is coming at all?
- [x] why is it loading suddenly all files in those directories. i.e for "CLIENT - Kopie.GER" no first file exists
- [ ] all log entries have duplicated "" for paths

**Comment by Flamefire** [comment]
>why does the "skipping duplicate override file" message is coming at all?

Because I added it so it isn't silently ignored. It may hint at an error

> why is it loading suddenly all files in those directories

It has done that before. Check the function `LoadOverrideDirectory` and its callers. I'm not really happy with that but I'm unsure why it was used in the first place. The use case I can imagine is to override an already existing/loaded file which is not explicitly reloaded. I think I can add a check for that to see if it is used that way. If we remove it then it won't be possible to override e.g. files loaded at startup but not during loading of a game. I guess this allows e.g. an addon to override a GUI image. This will replace the GUI image loaded at start. But not back again when the game is closed or the addon is disabled and another game is started. So this might not be useful at all. @Spikeone thoughts?

> all log entries have duplicated "" for paths

Ah yes. `bfs::path` get quoted when printing. Not sure how to handle this: Either use `.string()` to avoid this or remove the quotes from the log template but as that is translated the translations will be missing then.

**Comment by Flow86** [comment]
but before it did not try to always load all files from the lst directory, only if there is a directory named like it. I think thats the point on finding the files there.

example:

explicit load request: RTTR/LSTS/language.ini  -> should search for a RTTR/LSTS/language.ini/ directory, not trying to load everything from RTTR/LSTS/

I also had one unknown file in my directory (CLIENT.GER.BAK) - where I got an error "BAK unknown filetype" -> exit - this should not happen that it bails out if there is a file - this should be ignored.

**Comment by Flamefire** [comment]
> but before it did not try to always load all files from the lst directory, only if there is a directory named like it. I think thats the point on finding the files there.

No, you are confusing things here. This is what happens:
- We have override folders. One of them is `RTTR/LSTS`
- We load a file by name, e.g. language.ini. This searches in all override folders for files and folders named `language.*` and loads the collected files in order
- Then all files from all override folders are loaded. See the log message `Loading LST,LBM,BOB,IDX,BMP,TXT,GER,ENG,INI files from ...`. As you can see it explicitely loads all those files

> I also had one unknown file in my directory (CLIENT.GER.BAK) - where I got an error "BAK unknown filetype" -> exit - this should not happen that it bails out if there is a file - this should be ignored (it can be logged though).

This is because the override search for `client` finds it as a matching file (all extensions stripped and converted to lowercase). IMO bailing out is the right thing to do. It is a user error to put a wrong file there. The program cannot know if that is a file which accidentally matched or if the file was supposed to be loaded but was faulty. Hence bail out and let the user resolve it instead of silently continuing. Who reads the log when everything seems to work?

> we could propably run it over the language files too

If you got an idea how to do that easily can you tackle that?

**Comment by Flamefire** [comment]
I did a quick investigation on this as we should fix it before the release. The whole `RTTR/LSTS` folder is a problem: We currently add it as an override folder but don't use it as such. Current contents: `CLIENT.GER   CREDITS.LST   firework.LST   fonts.LST   GAME   io_new.LST   languages.ini   logo.bmp  'lst files loaded at start'   menu.bmp   RTTR.LST`

The problem now is when we load e.g. the fonts by explicit path then that is added to the list of files to load, then override folders are searched for overrides finding the same file causing the "duplicate" message. This shows a mistake on our side: We use it as an asset and as an override folder.

Proposed solution: Only use 3(-ish) override folders:
- A rttr override folder where we override files that we need to. This is basically the contents of the `GAME` folder now
- A folder with overwrites for addons (1 per addon) so addons could swap e.g. the catapult building
- A user override folder

Proposed structure:
- RTTR/assets (all from RTTR and RTTR/LSTS except MAPS, MUSIC, texte, gamedata, basically everything that can be loaded directly  by `LOADER.LoadFile`)
- RTTR/asset-overrides (everything from RTTR/GAME)
- RTTR/addons/{addon-id-as-hex} (renamed folder Addon_0x00000006)
- <RTTR_USERDATA>/LSTS (keep name for compat but ignore the GAME subfolder)

Remove the function which loads everything from the override folders.

This paves the way for loading assets by id only and let the loader (or a new class) figure out where it is.

Removing the GAME folder: We don't need it. It is not possible to overwrite GUI files because we don't reload them on game exit. Hence having a folder which is only active during game loading is not required. Those files will still be loaded on game start because we explicitely do that. It doesn't hurt to keep them with the other (currently none) overrides.

@Flow86 @Spikeone Thoughts? Agreed?

**Comment by Flow86** [comment]
sounds quiet good!

**Comment by Spikeone** [comment]
The charburner then should be moved to the addons folder as well, shouldn't it? As well as the BQ indicator icons. But guess that was just an example.
What happens if two addons override the same graphics? Maybe we need a list for all additional graphics, so one doesn't have to check any used ID.

Just some morning thoughts, I actually do not care about the structure but functionality ;) as long as someone tells me how (and I got some time) everything is fine^^

**Comment by Flamefire** [comment]
Good point. What are the file names for the charburner and BQ indicator things?

> What happens if two addons override the same graphics?

Depends. Same archive: Not a problem, will be merged. Same resource (e.g. graphics): The one with the highest addonID wins. Can't do anything about that so :shrug: 

> Maybe we need a list for all additional graphics, so one doesn't have to check any used ID.

This could be documented. Any idea how and where? My take would be the RTTR folder and a Readme.md. It is important the docu isn't mistaken for a resource. Would that be something for you @Spikeone? You likely know the most about those files and such a readme would help for the first question above :)

**Comment by Flow86** [comment]
if we go with "resource-names" without "files" for the addons it would be fine I guess (for future).

**Comment by Flamefire** [comment]
Can you elaborate? "Resource-name" == "lowercase filename w/o extension", I called it RessourceId in the code IIRC and which is the key in the files-map of the loader. This archive and indexed file within is kinda hard to handle but well..
Anyway what I meant: How would that solve overriding the same graphics? And no I don't think we currently have it.

**Comment by Flow86** [comment]
I meant kind of "named" resources - like "roman_hq" or something like that. or "cursor" or "button_background_red" or whatever.

Perhaps we should keep it simple for now, since we are not in the problem having override conflicts

**Comment by Flamefire** [comment]
I dream of that too, but who is gonna name all the thousand files and map those to archives and indices? It would solve the history edition compatibility though... But it is to much work (and boring work too)
