### ISSUE TITLE
Game crashes on closing with custom tracks

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1280]
When you load a custom track in the music player and close the game, the game will crash uppon closing

**Comment by Flamefire** [comment]
Uff this is hard... Working on it...
FTR: The cause is that we allocate a shared handle in the audiodriver dll. The dll gets unloaded and makes the allocation invalid (it seems dlls have separate heaps)

What we have:
- The loader has the archives/files containing the sounds
- On first playing it a `SoundHandle` is created and stored in the archive
- When the `SoundHandle` is no longer referenced the sound should be unloaded
- So it is ref counted and can be copied around
- When the audiodriver is unloaded all Sounds are unloaded too and the `SoundHandle`s are set to invalid
- The driver needs to store data for each `SoundHandle`, e.g. the bytes of the sound, which it does in a `SoundDesc`
- Currently the `SoundDesc` (virtual class) also stores the "isValid" flag, but this causes the crash: The SoundDesc gets deallocated (purged) when the driver is unloaded and the main program tries to check the isValid flag

Solution: The isValid flag must be allocated by the main program. I'll see how to do that...
