### ISSUE TITLE
How to represent game time

### ISSUE THREAD

**Issue by JonathanSteinbuch** [Return-To-The-Roots/s25client#1317]
Hello,

I would like to discuss how ingame time is supposed to be represented. As far as I can tell ingame time occurs explicitly in the statitistics window in the original.
![timeStatistics](https://user-images.githubusercontent.com/711115/102547750-f21c4b00-40b9-11eb-8373-ff887f769ebe.png)
Here the minutes displayed are the time it would take at 40ms per game frame (i.e. fast speed).

It occurs differently in tournament mode.
![timeTournament](https://user-images.githubusercontent.com/711115/102548626-38be7500-40bb-11eb-879a-2c7c2c1a5992.png)
Looking at the code for this, the minutes displayed are computed with the game frame length corresponding to the speed the game is actually run at (this means that under perfect conditions this should be the actual time the tournament game takes)

At other places actually game frames are displayed, though I feel those are more like debug features, so not as relevant:
![timeGameFrames](https://user-images.githubusercontent.com/711115/102548998-bc786180-40bb-11eb-8269-81a468b3ea09.png)

Those are all the instances I found where ingame time is represented.

In my economy mode implementationI went with the actual time under ideal conditions (as in the tournament length, after a question by @Flamefire). It is displayed in two places.
![timeEconomyLength](https://user-images.githubusercontent.com/711115/102549322-33adf580-40bc-11eb-999c-2371e44058b1.png)
![timeEconomic](https://user-images.githubusercontent.com/711115/102549338-36a8e600-40bc-11eb-9a7c-00d324483fbe.png)

So my question is how should time be displayed?
1. Assuming a reference speed (as in the statistics, although I guess normal speed as reference would be more intuitive). Pros: Simple. Makes game states after the same elapsed time more comparable. Was used in the statistics in the original Settlers 2. Cons: Can be confusing when you don't play at the reference speed (especially if you want to set a game length as in tournament or economy mode)
2. With actual time under ideal conditions (as in the tournament length). Pros: Is actually true (apart from the fact that currently frame times are wrong when you use hardware vsync, which I plan to fix) Cons: Not very comparable between different speeds
3. By game frame. Pros: Is definitely true. Comparable. Cons: The user doesn't know what a game frame is. Also quite unwieldy to write 22500 GF instead of 15min

Other options:
4. By a proxy for game frames (for example a "year" could be 45000 GFs or something)
5. Leave the differing representations as they are but write in the info texts how the mentioned time should be interpreted.
6. Don't do anything
7. ?

Is there maybe already some guidance on this, did this question come up before? Do you even see this as an issue?
Personally I would veer towards option 5, but I am not sure. Having a consistent way to represent time would also be nice, instead.

Best Regards
Jonathan

**Comment by Flamefire** [comment]
This is a very good issue. :+1:
Let me start with some (call it) observations:

- You can set the GF length at game creation time
- Ingame you can change the GF length again (+/-)
- GF is something opaque to the players and mostly an implementation detail (so yes, this is mostly debug info, or rather "advanced" settings)

Hence I would NOT measure anything player visible in GFs. So not option 3.
My take would be: The reference speed is the GF length set at game creation time. So all conversions to real time are done based on that. When the speed is changed ingame the observed time will change too which is IMO expected, however this should be written somewhere player visible.

The upside is: We can have everything consistent. E.g. the statistics window: How could that display the "last 15min" when the GF length could have changed multiple times in those last 15min? Hence we need a reference time. Choosing the time the player set at game creation time is likely the best as most players (?) won't change that during the game and IIRC the speed-up icon displays the speed relative to that too.

PS: As for the correct handling of GF execution time let's discuss this in an issue and come up with a design first. I think this is very important but also easy to get wrong. So we should get it right in all circumstances which may be hard given we have to synchronize over multiple clients.

**Comment by Spikeone** [comment]
As far as I remember the original didn't change anything on speed up either, so if gamespeed was x2, the "you haven't saved since 30 minutes" message popped up every 15 minutes.

I as an "old" settlers 2 player would expect, that the time format is always based on normal game speed as the original was. 

As for the windows:
We should keep the original format for the original window in my opinion, writing someting like 1.2h (with lower speed) just seems... strange. BUT in my opinion we should scale the statistics accordingly, means 15 minutes should be 15 minutes, no matter what game speed you use or if you change that.

Tournament mode:
We should remove them. There is no tournament planned anymore and ranking should be removed as well.

Gameframes visible:
The Debug display (upper left) should be hidden by default anyway as it's for debug only. I'd still keep it as reference as you need it for jumping. 
The post office window is wrong:
![grafik](https://user-images.githubusercontent.com/1276342/102594575-a8ae1900-4116-11eb-83d8-f0f13b5b8478.png)
In settlers 2 it displays the time on normal speed and does not scale with gamespeed.
The Jump To option should use gameframes.

Economy mode:
I don't know what that one is (yet) :D So I guess the 30 min option at normal speed would be 15 min on very fast then? Guess you have to produce something in a given time. I really think those times should be displayed as "on normal" speed.

Any other time display should be scaled by game speed in my opinion.
So the post office may show 01:00:00 even if you have been playing in real time since 40 minutes. Same goes for autosaves, a 5 minute autosave may occur every 3 minutes on higher speeds for a simple reason: there is more happening in the same amount of real time. As for that progress window, I'd also simply count "seconds" faster, at least thats what I'd expect as in Sims etc. where ingame time simply runs faster than before so a second is not a second.

**Comment by Flamefire** [comment]
Good input @Spikeone!

IMO the most important thing is consistency. So if we scale time by gamespeed it has to be done at every place, doing it in some places only is confusing at best and wrong at worst. I.e. the statistics window: There is no way to make it really "the last 15min" if you change the speed inbetween. Obviously we could make a real time timer and gather statistics at every real 15min, but then what happens when there are lags or the game is paused? That would look really bad IMO.
Also in old S2 you could not change the game speed at startup could you?

A point for choosing the startup speed as the reference for all ingame speeds: If you setup your game with e.g. "fast" and a length (in tournament or economy mode) of 30min you want to play 30min not 20, don't you? So all scaling would be relative to that. So if you change the speed ingame to twice the start speed, time would run twice as fast. This matches the icon we currently show for faster/slower speeds.
Also do players very the speed ingame often? If not choosing the startup speed as reference will make real time and shown time the same no matter which speed is chosen at startup.

**Comment by JonathanSteinbuch** [comment]
From both your inputs I gather that you agree with each other that during a game the time should be in reference to a fixed game frame length. You disagree only what that reference game frame length should be: @Spikeone thinks it should be normal speed, @Flamefire thinks it should be the game speed chosen at game start. 

Of these two I agree with the second, mainly because of the game length options for tournament or economy mode.

There is also of course the possibility to make the reference speed an option, but I think this might be confusing by itself.

**Comment by Flow86** [comment]
Since the reference is almost everywhere the "normal" game speed, we should also go with that for everything else

**Comment by Flamefire** [comment]
Is it? The statistic step uses it, but that's it. The tournament uses the current GF length, the economy mode is new so I wouldn't count it and `FormatGFTime` (and hence e.g. pacts) also use the current speed. And the speed indicator is relative to the start game speed. Hence I'd rather say almost everywhere we use the current game speed and where we need a reference we use normal speed in 1 place and start game speed in 1 place, so 1 vs 1 there. 

As the "current game speed" can vary it isn't really useful, so the second best is the start game speed, which in almost all cases is the same as the current game speed.

**Comment by JonathanSteinbuch** [comment]
Okay, it seems there is no consensus on this.

How about the following: 

- Make it the default that default speed is the reference speed as @Flow86  and @Spikeone prefer.
- Add an addon option to instead use the chosen speed at game start as reference speed for timekeeping. (To me it makes more sense as an addon option than as a settings option as it should be the same for all players playing together)

Any objections to that?

**Comment by Flamefire** [comment]
I think we should simply decide on one option and use it consistently.

As mentioned we currently mostly use the current speed as the reference because FormatGFTime  uses it which is a strong point for using the start game speed to keep it almost the same as-is. 

A point for using normal is the closeness to original game, although that didn't allow changing the speed ingame. And the statistic currently uses that as reference too.

**Let's vote in this comment (the smiley button right top):**

- React with ❤️  for reference is start game speed
- React with  🚀 for using normal game speed.

And in 14 days count and use that in case anyone else wants to join in.

**Comment by JonathanSteinbuch** [comment]
As of 14 days later it stands two to one for having normal speed as the reference. Consequently, I plan to prepare a pull request making the chosen adjustments sometime this week.

**Comment by Flamefire** [comment]
It is actually 2:2 (sorry, didn't cast my vote earlier as I thought it of being implicit there, my bad) but anyway: Feel free to prepare a PR as proposed.
If we have the stuff in place which unifies the reference time (make sure to have it a named constant somewhere using the GF_Speeds array for clarity) for the whole code then changing it later (if the experience/users show that the other option would have been better), then that change will be easy.
