### ISSUE TITLE
Add-on state change after save-load

### ISSUE THREAD

**Issue by RM87** [Return-To-The-Roots/s25client#1337]
Add-on state is incorrectly loaded after resuming a saved game.

Demolish building after resource exhausted (was off during game setup and also in main menu options, is on after loading game).

**Comment by Flamefire** [comment]
I can't see any obvious issue. Do you have a savegame/replay to reproduce?

**Comment by RM87** [comment]
[2021-01-07_22-19-10.rpl.zip](https://github.com/Return-To-The-Roots/s25client/files/5788346/2021-01-07_22-19-10.rpl.zip)
Demolitions happen at GF 28076  and GF 28151 .

**Comment by Flamefire** [comment]
That replay has the demolish setting enabled. Can't tell if that should be, but that's what the game file says.

What I also tried:
- create a new game
- in game lobby setup addon settings so that demolish is disabled
- start game
- save
- load that game
- demolish still disabled

Maybe you did accidentally enable it during game setup?

**Comment by RM87** [comment]
A bit doubtful but as I am unable to reproduce this at the moment also then closing
