### ISSUE TITLE
Improvements for random water maps

### ISSUE THREAD

**Issue by vader1986** [Return-To-The-Roots/s25client#1360]
Hi guys, 

I like to discuss how to improve a particular type of random maps - the water maps. 

There are a few things I don't like about random water maps at the moment:
1. There could be more "randomness", right now there's always a fixed (big) island in the center surrounded by a fixed number of islands (1 for each player - let call them "home islands")
2. On larger maps the home islands are huge - sometimes it's even hard to find the next harbor position for a player. Also, due to the size of the home island, there's probably very little motivation for players to reach another island for more resources (especially mountains). 
3. The harbor positioning in general is a bit odd. This is the way it currently works:
* find all coasts (connected nodes with a water-land-transition)
* ignore all coasts with less nodes than `(map width + map height) / 4` (coast is considered too small for harbors)
* for all remaining coasts place `N = number of coast-nodes / 50` harbors (each harbor with maximum distance to other harbors of the same coast)
4. ... I'm sure there's more to complain about! ... (since I wrote the random map generation code feel free to do so!)

I got a few ideas myself, how to improve the water map type for random maps. But I'm hoping for other peoples' input as well. Here are a few thoughts:
1. We could introduce more "randomness" by
* choosing a random point as central point for the "main" island (very easy code change, not too much improvement though)
* adding random "small" islands (especially for larger map sizes)
2. Maybe upper limit for size of "home islands" and fill the remaining water space with additional small (initially unpopulated) islands

**Comment by Flamefire** [comment]
> ignore all coasts with less nodes than

This means **islands** with less nodes than, doesn't it? Otherwise: What exactly is this meant to filter? Where could this be "to small" for reasonable islands? I'd make this independent from the map size: Every islands which is at least x nodes (find x by experimenting) gets 1 or more harbors. This prepares for more islands.
Besides that I like the harbor placement in general

Ideas:
- Make the amount of islands configurable (probably by fixed steps such as "few - many". In the smallest setting you get what you currently have: 1 island per player and a larger one in the middle.
- Bound the player start islands (both upper and lower). To choose limits, the map size, number of players and amount of islands should be used. An absolute upper and lower bound (additional) could also be useful: E.g. the player islands are not too big so players need to go to the (now bigger, due to map size) main island. The more islands that should be made (per setting) the smaller the player and main island becomes. Maybe take a look at existing maps how a human would design it.
- At the maximum setting, the "main island" should be bounded by the same size bounds as any other island making it not special at all while keeping the concept of a main island (which IMO simplifies the code)

I could imagine generating a map as usual and then shifting the whole map by a random offset (IIRC you can do that in steps of 2 in x and y by wrapping nodes around). It would still be the same map, but just look slightly different to given an appearance of randomness ;)

**Comment by vader1986** [comment]
> This means islands with less nodes than, doesn't it? Otherwise: What exactly is this meant to filter? Where could this be "to small" for reasonable islands? I'd make this independent from the map size: Every islands which is at least x nodes (find x by experimenting) gets 1 or more harbors. This prepares for more islands.
> Besides that I like the harbor placement in general

I agree, this should be for all islands of a minimum size. Just explained how it currently works. Probably also worth thinking about the number or harbors per island. I think one way to go could be:
* at least 1 harbor per island of minimum size
* up to N harbors (fixed number?) per island - depending on the size of the island

> Make the amount of islands configurable (probably by fixed steps such as "few - many". In the smallest setting you get what you currently have: 1 island per player and a larger one in the middle.

Sounds good! 

Also, I wonder if it is worth applying the settings for the number of islands to the mixed map. That way there could be a few islands around the center continent where all players start. 

> Bound the player start islands (both upper and lower). To choose limits, the map size, number of players and amount of islands should be used. An absolute upper and lower bound (additional) could also be useful: E.g. the player islands are not too big so players need to go to the (now bigger, due to map size) main island. The more islands that should be made (per setting) the smaller the player and main island becomes. Maybe take a look at existing maps how a human would design it.

Sounds good as well!

> At the maximum setting, the "main island" should be bounded by the same size bounds as any other island making it not special at all while keeping the concept of a main island (which IMO simplifies the code)

Yeah, I think that wouldn't be too difficult to achieve.

**Comment by vader1986** [comment]
Actually, I remember why I considered coast (size) instead of island (size) for harbor placement. There was an edge case when you have a large island with lakes inside. A better solution to resolve this would probably to find the "outer" coastline of each island for harbor placement. Just not sure yet how to find the "outer" coastline of an island ... *thinking*

**Comment by vader1986** [comment]
Actually, found the solution. Just find the coast with the minimum (or maximum) point (in either x- or y-direction).

**Comment by vader1986** [comment]
Thanks for your ideas so far. I'll pick it up next. It might take a while since I'm quite busy from work this week (and probably next).
