### ISSUE TITLE
s25client crashing: pure virtual method called

### ISSUE THREAD

**Issue by yallie** [Return-To-The-Roots/s25client#1449]
Hello! 

Not sure how do I report the issue properly, terribly sorry.
I am running the latest s25client.exe build on Windows 10.
The game is crashing, and all I see in the console log is this message:

>pure virtual method called
>terminate called without an active exception

The log file has no messages related to the crash.
The game crashes on the "Good old times" map by BlueByte.
I've got a replay file that shows the last minute before the crash.

The crash happens randomly when I do something with the game objects or when I save the game.
The game also crashes when trying to save the game after the replay finishes.
Here is a screencast on Youtube:

[![s25client crash](http://img.youtube.com/vi/tlJGHLUmy4I/0.jpg)](http://www.youtube.com/watch?v=tlJGHLUmy4I "s25client crash")

The replay file, the savefile and the map is in this zip archive: [crash_save_replay.zip](https://github.com/Return-To-The-Roots/s25client/files/7428438/crash_save_replay.zip).
Please let me know if I can somehow improve the bug report.

Thanks :)

**Comment by Flamefire** [comment]
Ok found the issue. At 52/42 there is a geologist from player 0 that was called to the flag from the military building which was then captured by player 3.
However the geologist is still working there when the building and flag gets destroyed but due to it not beeing reset when the flag was captured it is not notified which means it has a dangling reference to the destroyed flag.

**Comment by yallie** [comment]
Awesome! :)
