### ISSUE TITLE
Forester production in overview always 0%

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1454]
See:
![grafik](https://user-images.githubusercontent.com/1276342/139910493-400de715-f744-46d8-ad21-0fd7206a19a8.png)

**Comment by Flamefire** [comment]
While checking this against S2 I noticed this:
![Unbenannt](https://user-images.githubusercontent.com/309017/144899502-0f5e40e2-50d4-482f-a1fb-fb82982a321f.png)

While in S2 the forester has a production rate it does not show up in the window. We basically mirrored that in S2 by only calculation average productivity for buildings that actually produce something.

So 2 solutions:
- Either don't count the forester as a producing building for stat purposes similar to original (neither shown in this window nor used to calculate productivity statistic in the stats window), i.e. only change is the removal from this window
- Add it to both (show productivity here and count in the stats window)

The 2nd solution is a minor issue: The lookout-tower is similar to this: It produces nothing but otherwise behaves like a regular building. We'd need to add some special handling for that as it shouldn't have productivity of neither 0% nor 100%, should it?

**Comment by Spikeone** [comment]
I personally don't care for any of those statistics, so my opinion might be biased.

I'd go for the 2nd idea. It doesn't really matter for the forester in the productivity statistics, if someone wants to boost it, simply build wells. But it might be worthy looking at your foresters if they have enough space to plant treest or if they are ineffective. So having a central percentage might be a good thing (possibly, I don't use it for that case but thats the only use I can think of).

Also I do not get whe the lookout tower is so special compared to military buildings. Maybe the inheritance causes the problem you describe but from a not code knowing perspective, it should behave for statistics like a military building - counts towards the building statistics but not productivity.

**Comment by Flamefire** [comment]
Military buildings can be attacked, hold land etc.
The tower is like a well but it does nothing... It just is.

**Comment by Spikeone** [comment]
And a storehouse? Compared to a Harbor/HQ it can't be attacked, it does not produce anything and has no productivity either

**Comment by Flamefire** [comment]
Yeah it is a bit tricky. See https://github.com/Return-To-The-Roots/s25client/blob/master/libs/s25main/gameData/BuildingProperties.cpp

Anyway: So this would be the plan:

- Show actual avg. productivity of forester in this window
- Include it in the total economy avg. productivity

Correct?
Note that this is different to original S2 which only lists actually producing buildings.

Also: Change the order to match the S2 order or keep as-is? If changing: Where to put charburner and forester?

CC @Flow86

**Comment by Spikeone** [comment]
Oh, how is the Catapult exluded?

In nearly all cases I'd go for the original way. Yet the order seems a bit strange. I'd expect it to either:
- order by build menu (woodcutter, forester, quarry, fisher, hunter, well, sawmill, slaughterhouse, mill, bakery, iron smelter, metalworks, armory, mint, shipyard, brewery, farm, pigfarm, donkey breeder, charburner, gold mine, iron mine, coal mine, granite mine)
- order by production (woodcutter, forester, sawmill, quarry, fisher, hunter, well, farm, brewery, mill, bakery, pig farm, slaughterhouse, donkey breeder, charburner, mint, iron smelter, armory, metalworks, shipyard)
- order as original (put the forester after the woodcutter, put the charburner after shipyard), extending both columns by 1 row

As said, I do not use that menu, so I'm not sure what the best way is. I don't think we are bound to the original here, as it does not change anything but improves it. On the other hand, we should try to stay as close as possible. So I'd rank my described options 3 > 1 = 2

**Comment by Flamefire** [comment]
> Oh, how is the Catapult exluded?

It does not produce anything -> Not included in productivity calculations. This (previously) was the one and only, very simple condition. And I kinda like it...
And this window has a separate list of buildings as the order should be configurable (by us)

Ok, so 
> order as original (put the forester after the woodcutter, put the charburner after shipyard), extending both columns by 1 row
