### ISSUE TITLE
Cleanup Buildsystem

### ISSUE THREAD

**Issue by lweberk** [Return-To-The-Roots/s25client#146]
Move build automation and all peripheral stuff out into own repository to wrap the clients one.

s25client should only contain src, cmake, submodules and compile with "cmake; make" directly from root dir.

This makes packaging and setting up buildservers easier.

Blockers: current buildserver... probably hard-depends on this repository layout.

**Comment by Flow86** [comment]
you can use cmake ; make (from any non-source-dir, since out of source builds are mostly a better way)

the cmake.sh wrapper is only for easier use of the cross-compiler selection, but not needed at all.

I also dont know what you mean with "move build automation etc". what stuff do you want to move?

**Comment by Flamefire** [comment]
I also think the current system is ok. Whats wrong there? You download the repo with submodules, run cmake und make. Done...
