### ISSUE TITLE
Lava not animated on Wasteland

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1514]
Lava is no longer animated on wasteland maps. Maybe this is related to #1509

**Comment by ottml** [comment]
Extracting the palette animation from the TEX6.LBM shows the following:

> Palette animations V1
> 1	1536	active	forwards	248	251
> 2	0	inactive	backwards	208	223
> 3	0	inactive	backwards	224	239
> 4	0	inactive	backwards	40	47
> 5	0	inactive	backwards	8	15
> 6	0	inactive	backwards	48	55
> 7	1227	active	forwards	248	251
> 8	0	inactive	backwards	112	127
> 9	0	inactive	backwards	64	75
> 10	1995	active	forwards	240	247
> 11	0	inactive	backwards	176	191
> 12	0	inactive	backwards	96	103
> 13	0	inactive	backwards	76	79
> 14	0	inactive	backwards	16	24
> 15	0	inactive	backwards	25	31
> 16	0	inactive	backwards	32	39

The palAnimIdx for lava animated on wasteland should be 7. But in the data\RTTR\gamedata\worldwasteland.lua the palAnimIdx index is set to 11 for all lava terrains. Therefore the lava is not animated anymore. The issue is not related to #1509.
