### ISSUE TITLE
Game run from this save always crashes

### ISSUE THREAD

**Issue by balwierz** [Return-To-The-Roots/s25client#1559]
win32 version v20230302-60d3d9470be818b02f1af32f53a545bd8d30d041
Steps to reproduce:
* load the attached save
* set yourself to the first player
* leave the second player as dummy (this actually does not matter, you can have another player)
* Do nothing for about 3 min
* The game will crash

[dfhg.zip](https://github.com/Return-To-The-Roots/s25client/files/10920632/dfhg.zip)

PS.
Also at the same game there started to appear less serious bugs before: Some goods are not transported near the blue player's harbour. Blue player cannot attack the enemy's harbour although it is visible, there are enough soldiers etc. Blue player has some buildings not being built (despite enough resources and builder present) near the harbour.

**Comment by wichern** [comment]
What I see in the game is that the Harbour is being attacked. The crash happens right when the enemy soldiers enters it:
![Screenshot from 2023-03-23 11-36-57](https://user-images.githubusercontent.com/47030768/227178762-8b98fcc8-6cc9-49ad-80bb-711e6defc2bc.png)

The crash occurs, because this condition is not true:
https://github.com/Return-To-The-Roots/s25client/blob/master/libs/s25main/figures/noFigure.cpp#L429

The actual value of the GOT at that position is `GO_Type::Fire`.

**Comment by wichern** [comment]
I think I found the bug. I will create a pull request.
