### ISSUE TITLE
No sound with pipewire

### ISSUE THREAD

**Issue by abergmeier** [Return-To-The-Roots/s25client#1646]
I am using Pipewire for providing Pulseaudio but somehow s25client never shows up as a sound client.

**Comment by Spikeone** [comment]
Well, I have no idea what pipewire does or why it is required. But it looks like a somewhat common problem.

Maybe some of those solutions help: 
https://www.reddit.com/r/archlinux/comments/m3jjbq/no_sound_in_certain_games_with_pipewire/
https://www.reddit.com/r/linux_gaming/comments/poiw8p/im_having_sound_problems_in_steam_with_pipewire/ (maybe thats the cause, since we use SDL)

But sadly I have no other idea, nor what would cause this problem (in general, since any other application could be affected as well).

**Comment by Spikeone** [comment]
Closing since no response from OP
