### ISSUE TITLE
VirusTotal detected virus

### ISSUE THREAD

**Issue by mrtnrocks** [Return-To-The-Roots/s25client#1654]
Hello, 

I downloaded Version 20240312 windows x86_64

VirusTotal flagged the file [s25rttr_20230814/libvorbis-0.dll](https://www.virustotal.com/gui/file/a178f069a33810a963955dc152ebc20c39257125acb53f3344b27f47a3211338) as Virus.Win64.Dupshirk

Is this a problem?

Thank you

**Comment by Flamefire** [comment]
@Flow86 Can you check which version of the DLL gets bundled by Jenkins and where that comes from? It is not https://github.com/Return-To-The-Roots/dev-tools/blob/ab8e8aadc6d79599325a584b95d1132eafe5fc88/msvc/bin/x64/libvorbis-0.dll (check the checksums)

FTR: The 0.9.5 stable release used a different DLL. But the flagged one is used as far back as I can check the available downloads of nightlies.

@mrtnrocks I don't think it is an issue but you can try using the DLL from the above link. It might not work with the official builds though as they are built differently (using MinGW, not MSVC) But maybe that is already the issue: MinGW flagged just because it is "unusual"   
You could also try using the DLL from the 0.9.5 release with the current nightly. But again I assume this is simply a false positive by one to eager scanner

**Comment by mrtnrocks** [comment]
Thank you for helping, but I think I will go with the stable release 😉

**Comment by Flow86** [comment]
the libvorbis and all other SDL_mixer dependencies come directly from the SDL_mixer package.
