### ISSUE TITLE
Harbor gets removed although it should be valid

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#1656]
On the map Pathfinding_01 the harbor at 76:66 is removed, although I don't see why it should since there is at least one costal spot nearby that could be used by ships.

![grafik](https://github.com/Return-To-The-Roots/s25client/assets/1276342/ee556518-1e22-49c7-be2f-26047bf367ef)

**Comment by Spikeone** [comment]
Now that I was thinking about it, it's probably correct - since that harbor spot might allow loading and unloading ships but no sea attacks since that particular spot won't allow people to walk over. Just asking @Flamefire for confirmation then (and I need to fix the map then)

**Comment by Flamefire** [comment]
It must have a coast spot around it. Except for the NW point. A coast point IIRC is a point on land with a water spot around it where the water belongs to a shippable sea. The only such point in your example is 75:65. However the NW point is skipped because it often leads to unusable harbors: https://github.com/Return-To-The-Roots/s25client/blob/fd16215cfb8b6b3cb35fb002578358d942600757/libs/s25main/world/MapLoader.cpp#L466-L468

So yes this is intended
