### ISSUE TITLE
New Addon: Wine Buildings/Wares/Jobs

### ISSUE THREAD

**Issue by aztimh** [Return-To-The-Roots/s25client#1669]
Finished working on graphics for a new addon that adds new wine buildings/wares/jobs as an optional addon.

https://github.com/aztimh/RTTR-Wine-Addon

I've included all the the documents for how it's all supposed to function and calculated the XY nation offsets for things like work windows, chimney smoke, stop production X signs.

Also made txt documents that give a quick reference for the graphics contained within the LST files.

I'm not a programmer (yet), so I am sharing this so someone can program it as an addon.

**Comment by ottml** [comment]
<img width="1920" alt="wine_addon" src="https://github.com/Return-To-The-Roots/s25client/assets/33401986/cb8e708e-298b-4ce1-a87d-3a70500dfdca">

**Comment by aztimh** [comment]
Oh wow! That's so awesome! I'm actually in the process of fixing some of the larger buildings which were a bit wide when built next to other ones so it will slightly alter some of the offsets. But I hope to have the last one finished tonight!

I'm not sure how to compile it actually, I've just been working on the pixel art and ideas mostly.

Thanks so much I'd love to test it out!

**Comment by Spikeone** [comment]
@ottml just asking: If the addon is disabled, are all the icons (inventory, settings screen) hidden as well? If so, could you also implement it for the charburner as well, if not, could you implement that since using the default s2 settings should not show these icons so player can get an original feeling :)

But great work adding this so fast :) Thanks for your contribution(s)!

**Comment by ottml** [comment]
> @ottml just asking: If the addon is disabled, are all the icons (inventory, settings screen) hidden as well? If so, could you also implement it for the charburner as well, if not, could you implement that since using the default s2 settings should not show these icons so player can get an original feeling :)
> 
> But great work adding this so fast :) Thanks for your contribution(s)!

No at the moment they are always shown. But when changing this for the wine addon this should not be a problem to do for the charburner too. The only problem is gui's use mainly hardcoded sizes at the moment for in game windows. :)

Another  question: Is there a possibility to trigger a build over the ci from a branch/Pullrequest to get a install package that another user can download and use for testing? @Flamefire

**Comment by ottml** [comment]
> Okay I have reuploaded the WINE.LST after updating some offsets and fixing the temples so they don't clip across nearby buildings. Also updated the Nation Offsets text file for the new versions. Also unfortunately I forgot to include the Winter African Temple shadow initially so I've put that in but it means every building graphic after that is 1 higher now. I've fixed the WINE.LST glossary to help.
> 
> I _think_ that's everything.
> 
> I would love to test it out!

Nice. Should not be a problem :)

**Comment by Spikeone** [comment]
Also, if I'm not wrong, this addon isn't used by the AI yet, is it? We may need to brainstorm a bit on how an AI should use it (maybe after some test plays using this addon), since it's usage for the Charburner isn't optimal as well

**Comment by ottml** [comment]
> Also, if I'm not wrong, this addon isn't used by the AI yet, is it? We may need to brainstorm a bit on how an AI should use it (maybe after some test plays using this addon), since it's usage for the Charburner isn't optimal as well

Your are right :)
This is only a first draft implementation. I implemented only some stuff to see how nice the animation, buildings and workflows are. Th final will follow....

**Comment by aztimh** [comment]
@ottml My notes from testing the build so far:

Wine Addon Testing Notes:

Comments:
- I really like the idea of the Temple needing: 1 wine, 1 meat and 1 bread per cycle. It really makes it not too overpowered for being an infinite wildcard mine.

Suggestions/Considerations:
- Extend temple building GUI window down slightly so that it has the same space below the "3 wares in" as other buildings have below "2 wares in" (should also give room for the larger temples to not clip across the name of the building in the window).
- It seems transport of wine gets slowed to temples because all 3 ware inputs are foodstuffs. Is there a way to increase the priority of wine within foodstuffs so it is equal in transport priority to bread/meat?

Bugs:
- The new jobs display as "<building name> worker" in a warehouse instead of: Winegrower, Vintner and Temple servant.
- Charburner seems to now only place piles on farmable (fertile) terrain like the farm/vineyard when he should be able to do it on desert/beach terrain also.
- Grapes and wine are taken to a warehouse before the winery/temple even if there is space for them in the building to be processed. They are only taken directly to the building if you disable storage of grapes/wine in all warehouses.
- The Winery animation and work cycle is too fast. Should be equal to Mill in work time and slower animation for the work window.
- Fat grape carrier animation frames appear to be off by 1 (I'm working on some of the sprite offsets to smooth the walking animations that were a bit janky).
- Grape field shadows seem to be displaying wrong. In wine_bobs.lst graphics 27 to 31 are the 5 stages of the first type of grape field. Graphics 32 to 36 are the 5 stages of the 2nd type of grape field. Then graphics 37 to 41 are the shadows for the first type of grape field and 42 to 47 are the shadows for the second type of grape field. So the first field is #27 and its corresponding shadow is #37 (each one's shadow is numbered 10 more than the graphic for the grape field).
- The temple output ware icon should be wine_bobs graphic: 530. This can also be used for the default production setting icon (next to halt production like the shipyard). For iron ore, coal and stone we can just use their normal ware icons.

**Comment by ottml** [comment]
Wine Addon Testing Notes:

Comments:

- [ ]     I really like the idea of the Temple needing: 1 wine, 1 meat and 1 bread per cycle. It really makes it not too overpowered for being an infinite wildcard mine.

Suggestions/Considerations:

- [ ]     Extend temple building GUI window down slightly so that it has the same space below the "3 wares in" as other buildings have below "2 wares in" (should also give room for the larger temples to not clip across the name of the building in the window).
- [ ]     It seems transport of wine gets slowed to temples because all 3 ware inputs are foodstuffs. Is there a way to increase the priority of wine within foodstuffs so it is equal in transport priority to bread/meat?

Bugs:

- [ ]    The new jobs display as "vineyard worker" etc in a warehouse instead of: Winegrower, Vintner and Temple servant.
- [ ]    Charburner seems to now only place piles on farmable (fertile) terrain like the farm/vineyard when he should be able to do it on desert/beach terrain also.
- [ ] Grapes and wine are taken to a warehouse before the winery/temple even if there is space for them in the building to be processed. They are only taken directly to the building if you disable storage of grapes/wine in all warehouses.
- [ ] The Winery animation and work cycle is too fast. Should be equal to Mill in work time and slower animation for the work window.
- [ ] Fat grape carrier animation frames appear to be off by 1 (I'm working on some of the sprite offsets to smooth the walking animations that were a bit janky).
- [ ] Grape field shadows seem to be displaying wrong. In wine_bobs.lst graphics 27 to 31 are the 5 stages of the first type of grape field. Graphics 32 to 36 are the 5 stages of the 2nd type of grape field. Then graphics 37 to 41 are the shadows for the first type of grape field and 42 to 47 are the shadows for the second type of grape field. So the first field is 27 and its corresponding shadow is 37 (each one's shadow is numbered 10 more than the graphic for the grape field).
- [ ] The temple output ware icon should be wine_bobs graphic: 530. This can also be used for the default production setting icon (next to halt production like the shipyard). For iron ore, coal and stone we can just use their normal ware icons.

**Comment by aztimh** [comment]
@ottml hmm maybe the Charburner is doing that coz I tested what the build menus look like with the Charburner disabled and wine buildings enabled… then turned it back on. I can test it on the newest version if you like?

And yeah in terms of all the balancing: work cycles, etc we can refine that until it feels right.

**Comment by aztimh** [comment]
@ottml Yeah I did a test with the early build then. The charburner only does piles on fertile land or sand that is right next to fertile land. He wasn't putting any on completely sand terrain which he usually can.

**Comment by ottml** [comment]
> @ottml Yeah I did a test with the early build then. The charburner only does piles on fertile land or sand that is right next to fertile land. He wasn't putting any on completely sand terrain which he usually can.
> 
> Although it is possible this is already fixed in your updated build and this was just a bug in the early first build you sent me.

I accidently reduced the radius of the charburner. I think this leads to the problem.

**Comment by aztimh** [comment]
> > @ottml Yeah I did a test with the early build then. The charburner only does piles on fertile land or sand that is right next to fertile land. He wasn't putting any on completely sand terrain which he usually can.
> > Although it is possible this is already fixed in your updated build and this was just a bug in the early first build you sent me.
> 
> I accidently reduced the radius of the charburner. I think this leads to the problem.

@ottml Here's some notes from play testing the new build:

- Charburner is working properly again. Can place pillars on sandy terrain.
- Carriers do deposit grapes and wine straight into winery and temple now.
- I really like how you need to manage the economy now that you have to balance grain for meat or bread production to keep the temple running. Similarly the rates of wood to the sawmill/charburner/vineyard make it more interesting as games progress and you juggle the distribution of goods.
- Winegrower makes digging sound when harvesting grapes, this should probably be no sound or I can check if any would make sense here.
- Grape fields and grain fields can be planted right next to each other. They should block each other as they do to themselves to have a 1 space gap.
- The work cycles of the Vineyard/Winery/Temple seem to be a good rate but this can obviously be refined with play testing.

I'm gonna sort out the offsets so the winegrower doesn't bounce around so much while digging. I think we could keep the total grape field setup time the same but maybe reduce digging loop by 1 so the animation can play a bit slower like other digging animations.

**Comment by aztimh** [comment]
https://github.com/aztimh/RTTR-Wine-Addon

@ottml Uploaded the new versions of: wine.lst and wine_bobs.lst

wine.lst was updated as per Flamefire's suggestion in the PR so each building is numbered in a group of 9 images (updated the glossary text file).

wine_bobs.lst was updated to fix the digging animation for the winegrower and make other walking animations less jank.

**Comment by simulified** [comment]
sup
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 5; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```

**Comment by aztimh** [comment]
@ottml I think the only other thing I can think of is working out the coordinates for where workers and carriers disappear for each of the building’s new doors so they don’t look like they walk through the middle of it.

@Spikeone Is it similar to the XY offset for the open door graphic or is there a way to calculate this?
