### ISSUE TITLE
Audio driver not found in Linux Mint

### ISSUE THREAD

**Issue by Piotr-Wieczorek** [Return-To-The-Roots/s25client#1686]
![Zrzut ekranu z 2024-07-24 19-00-21](https://github.com/user-attachments/assets/c4e94266-47ae-4e14-9c1e-485d9b86b9d1)
GitHub site of the packages (libsdl2 libsdl2-mixer) has no instructions of installation in Linux.
https://github.com/libsdl-org/SDL_mixer
Terminal is too confusing to use for most of people (including myself) so the only option left is using Windows version via translation layer which works perfectly fine.

**Comment by Farmer-Markus** [comment]
> It's not that complicated just run this command to install the packages 'sudo apt-get install -y libsdl2-2.0-0 libsdl2-mixer-2.0-0'
It will ask for your password to install.
And thats all. Just one command. Good luck :D

**Comment by Flamefire** [comment]
@Farmer-Markus Thanks for the example. That works for Debian based systems (Ubuntu, Mint, ...) and is what is referred to by "package management" (`apt`/ `apt-get` is the package manager there)

Not sure how to make that even more clear without being to detailed as other distros might have other package managers.

**Comment by Farmer-Markus** [comment]
> @Farmer-Markus Thanks for the example. That works for Debian based systems (Ubuntu, Mint, ...) and is what is referred to by "package management" (`apt`/ `apt-get` is the package manager there)
> 
> Not sure how to make that even more clear without being to detailed as other distros might have other package managers.

Why are sdl and other libraries not included like in the windows version?

Is it a license problem? If not then I can create an example how it could be done.
Its very easy you don't need to change stuff in the code. You can export the "LD_LIBRARY_PATH" into the directory with the sdl binaries. This can be done with a single bash line.

**Comment by Farmer-Markus** [comment]
@Flamefire 

Why are sdl and other libraries not included like in the windows version?

Is it a license problem? If not then I can create an example how it could be done.
Its very easy you don't need to change stuff in the code. You can export the "LD_LIBRARY_PATH" into the directory with the sdl binaries. This can be done with a single bash line.

**Comment by Flamefire** [comment]
Because on Linux it is bad practice to ship your own libraries when they are easily available via the system package manager. No need to clutter the file system with things that are already available globally (or can be made available by "official" means).

It is a trade-off: Linux users are more likely to know how to use the commandline/package manager or configure-make-install-cycle to install things. There is even a FlatPak version of RttR if you prefer an all-in-one.   
On Windows it is more complicated to manage such stuff and there most users expect that stuff just works without any additional steps.

**Comment by Farmer-Markus** [comment]
@Flamefire 

Thats a point...
