### ISSUE TITLE
Buildings dont get ressources the longer the game goes / buildings get build 10 minutes later

### ISSUE THREAD

**Issue by MrBeanistderbeste** [Return-To-The-Roots/s25client#1715]
hello, i have noticed an annoying problem. in the beginning of a game ( stable or latest nightly ) every building has 100% productivity and get a lot of goods. the later the game goes the less goods get into a production building for example brewery. i have always a lot of goods in my HQ like grain or water and there is no traffic jam but the worker dont put it in the brewery so the productivity is low. last game i had the same problem with sawmills. low productivity because no trees in it. if i build buildings sometimes it happens that it takes 5-10 minutes that worker begin to put wood into the buildings. its like there is always a delay the longer the game goes.

[2024-11-12_15-46-19.zip](https://github.com/user-attachments/files/17732878/2024-11-12_15-46-19.zip)

**Comment by ottml** [comment]
I had a look into the attached replay. The problem is you have no obvious traffic jam on the roads but a traffic jam in your HQ. You have only three warehouses on a very big map including your HQ. And some wares like boards are only stored in your HQ. Usually the wares are delivered from the nearest warehouse. The goods and people ordered from buildings are added to the internal leaving queue of the warehouse the will come from. Only a ware or person can leave the warehouse at the same time. Poeple have always higher priority then wares. In the late game phase, when you build a lot of new buildings, or you have a lot of soldiers going in and out, the internal queue for the wares, which want to leave the ware house, is increasing rapidly. In the case of this replay we have over 200 wares in the warehouse queue waiting for being delivered.

**This leads to the impression the production buildings get too less goods or new build buildings to not get any wood or stone.**

 Here a short computation example to show the effect:
- Assume each 1s a ware is delivered out of the warehouse
- We have 200 wares in the queue
- We build a new building which needs wood
- The wood is placed at position 201 in the queue
- It takes 201 * 1s = 201s =3min 21s until the wood for the new building is delivered from the ware house

And because people have always priority it can take even longer if for example a lot of soliders or other people need to leave the warehouse.

**Comment by ottml** [comment]
So one solution for the problem would be to build more warehouses distributed over the whole map. So that not all wares come from the same warehouse. This has also the benefit the ways for the wares are much shorter.

**Comment by MrBeanistderbeste** [comment]
thanks for the answer. so its better to put different goods in different warehouses ? for example boards in 1 warehouse and stones in another ?

**Comment by aztimh** [comment]
It is better to build more warehouses further out as you expand outwards. Sometimes I build an extra sawmill near a new warehouse so it will get some boards and shorten transport routes. What you don't want is all of 1 resource to only come from 1 warehouse coz then it gets jammed as ottml said. If all the boards are coming from 1 warehouse and you place 20 building sites it will take longer for the boards to arrive to those new building sites.

**Comment by aztimh** [comment]
![Starmie](https://github.com/user-attachments/assets/1d9a58c0-4c34-479a-b65c-3f5e33492480)

See how as I expand out there are many Storehouses so it's not all choke-pointed into one central hub.

I have never encountered the problems you are referring to, or if I notice a lack of efficiency I make sure my roads are optimized and I have enough storehouses.

**Comment by MrBeanistderbeste** [comment]
but there is still a problem xD my production buildings are mostly near my HQ and so stones,boards etc will always be delivered to my HQ ( thats why my HQ is always full of goods ). if i build many warehouses ive still the problem that all goods go into my HQ. so isnt it better if i dont accept all goods in my HQ ? ottml said there is this queue. so it makes more sense to put different goods in different warehouses or ? so that the queue is lesser

**Comment by aztimh** [comment]
So once you have enough stone and boards you can use the X thing so new ones are delivered to other warehouses. Or the collection function to deliver some to another warehouse. Or build quarries/sawmills near other warehouses as you expand out.
