### ISSUE TITLE
Add RTTR defaults for addons

### ISSUE THREAD

**Issue by Flamefire** [Return-To-The-Roots/s25client#238]
We currently have S2 default settings for addons but no RTTR recommended settings.

Should we use RTTR defaults? If yes, what would be the default? For e.g. metalworks I'd use No ware on zero as RTTR default. Most of the other stuff should be similar to S2 defaults with only few recommended changes.

**Comment by BlOedsin** [comment]
Maybe instead of RTTR defaults a compromise is to have “activate all extensions”?
	- Tool ordering = True
	- Change metalworks behavior on zero  produce nothing
if that is activated the percentage of the tools should be 0 for all; otherwise it is not stopping to produce (or at least a button for everything to 0)
	- Disable coins by default = true
	- Enable charburner#
	- Improved alliance = true
	- Manual  road enlagrgement = true
	- Military Aid = True
	- Race Specific catapult graphics = True
	- Military Control = true (but that one is for sure a point of discussion; so maybe skip it)
	- See attack settings  enemy harbors block
(should automatically be in that setting if it is a sea map; otherwise you might start a game and forget that button  you can not continue)

Furthermore I would appreciate a button which let you choose if you lock the addon settings by loading a game or not. (E.g. you forget to select tool ordering or sea attacks) Before I could just save the game and load again; which I would do still if I am playing alone; For Network playing it makes sense, that you lock the possibility of later change in the settings.
PS: Is there a trick, to keep the in options->addons configured values if you update to the latest nightly? Would be nice, if you could save them and import them again after the update.

**Comment by Spikeone** [comment]
We agreed that we should not add rttr defaults that because even our team couldn't agree on the "best" settings.
I would rather like a config file selector where you could use the filename as config name and include all addon settings

**Comment by BlOedsin** [comment]
Exactly because defining rttr defaults is difficult, my proposal is more an “activate all button”. Which makes it faster to configure your settings of choice. So instead of activating a lot of things, I just click activate all and just deactivate those add-ons which I don’t want to have.

**Comment by Spikeone** [comment]
I'd like to have like a set of settings - maybe in xml, which you can load by yourself. So if a Player says "those are my ultra hardmode settings" he can just upload the .xml file which other people can download and then use from a menu instead of coding additional settings in the game itself

**Comment by Flamefire** [comment]
I think we agree not have RTTR defaults. rest in new issues if really required. (Settings reset on update is a bug...)
