### ISSUE TITLE
KI did not bild quarry

### ISSUE THREAD

**Issue by BlOedsin** [Return-To-The-Roots/s25client#263]
Hi Everybody!
I was playing today with the latest nightly built, and no one of the three computer player (easy, medium, hard) were building a quarry

. 
Stones were in Range of the HQ. They were building on other islands but only till they were running out of stones. As they had sawmill and lumberjack, they had for sure enough wood to build it.
I attached the related save game.

Link (7 days) to Savegame:
https://fil.email/1EV6dU

Any ideas why that happened?

**Comment by jhkl** [comment]
I started a quick AI game and saw multiple strange things: Farmers next to foresters. Woodcutter next to stones. Other woodcutters in plain field. Something is wrong!

**Comment by Flamefire** [comment]
@jhkl Can you check the recent changes in the AI again? And check if the same wrong things happen when you compile locally with a full rebuild? Looks like the AI is using the wrong constants for its resource map which might be caused by the changes or some left-over build artifacts.

**Comment by jhkl** [comment]
I will look into it.

**Comment by jhkl** [comment]
Initial filling of the resource maps was ignoring surface resources. Fixed that. 
But.
The resource maps in general are totally fucked up. Some commits in the past did some horrible things. There are some doubled method which aren't even called. Resmaps are overwritten in methods that should only be reading them, ...
I stopped reading at the comment
`//copy the value to the resource map (map is only used in the ai debug mode)`
and went to bed. Crying.

**Comment by Flamefire** [comment]
Git blame shows 4ff18dd4eaa0ce5334ed4ac4fe9e865ce1b9210c as the version this was added, if this helps

**Comment by ikharbeq** [comment]
The issue seems fairly new - I just jumped through 100k gf with full ai in the 27.8.2015 version and there all ai players worked as expected.

@ jh: I changed the resmap use a long while ago into 3 categories:
1. Resources that only decrease (fish,mines,stones,...) but also blocked-farmland and reachability: 
init, use and update resmap in the requested area when looking for a new construction site that uses that resource.
2. Resources that can also increase (wood,border,plantspace):
init, recalc for area that is requested instead of using & updating, copy new values to the map for debug.
3. Resources that seemed useless to me at the point: for now just builing-quality:
don't use, don't update - instead use the building quality info the 'player' has.

**Comment by Flamefire** [comment]
@ikharbeq Seems reasonable to me. IMO that should be documented and probably traits defined for that (mapping of ressource -> category) and make the functions handle those categories.

There was a bug in the recent refactoring that returned the subRes in most cases even when the surfaceRes should be returned. Can you check the behaviour with jhs current commit against the old one?

**Comment by Flamefire** [comment]
Bug is fixed. The problem was a huge function with the same block duplicated 4 or 6 times which I factored out into a new function. I just found, that one of those blocks hat a "-" sign where the others had "+" -.-

@jh or @ikharbeq  There is an unused class AIResourceMap. I actually think it is a good idea to factor all resource rating stuff out of the actual AI. The AI classes are to huge anyway. So if one of you can implement the use of AIResourceMap (and check if it does, what it should) it would be a great step forward I guess. This way all specific handling (what is updated and where) is encapsulated into a class and mistakes are less likely.
