### ISSUE TITLE
Game Crashes, when certain buildings of Ki become visible

### ISSUE THREAD

**Issue by BlOedsin** [Return-To-The-Roots/s25client#264]
I could reproduce the following error in a couple of ways.

![bild01](https://cloud.githubusercontent.com/assets/14259828/9836789/d3c43304-5a26-11e5-9736-e536e08cec19.PNG)

If my screen stays left of the area which became visible (no fog of war anymore) in the 2nd picture, there was no crash. 

![bild02](https://cloud.githubusercontent.com/assets/14259828/9836762/bb349f6e-5a25-11e5-8dd5-3476544cf8a0.PNG)

I could attack all military buildings left of that area, but this last one was not possible to be conquered. Cause even if it is visible by owning the watchtower as soon as you move your screen to far to the East, the game crashes. 
I had that issue already in other games, but this was the first time I could reproduce it in such a clear way. If appreciated, I can upload the save game as well. Just send an exploration expedition to reproduce.
Are there any know workarounds for that feature?

**Comment by Flow86** [comment]
hi feel free to upload the savegame and/or replay, otherwise we can't reproduce it

**Comment by BlOedsin** [comment]
Link to savegame (7 days)
https://fil.email/1EP27Z

**Comment by Flamefire** [comment]
Thanks for the savegame. The crash is reproduced here and probably related to the metalworker addon and the fix for that a couple of days ago. It will probably not happen if the behavior is set to "produce random tool" but this is not sure.

Dev info: Metalworker is drawn as walking but the current_event is NULL which leads to the crash. So either current_event is not loaded (unlikely), it is already reset or never set but the system still tries to draw a not working metalworker
