### ISSUE TITLE
Sound-Converter.exe is crashing

### ISSUE THREAD

**Issue by Blackwolf-Kuzoku** [Return-To-The-Roots/s25client#268]
Hi there. 

I'm using Settler 2 Gold from www.gog.com and the latest Nightly from 11th September 2015. 
If you delete the "Return to the Roots" - Folder in C:\Users\Yourname\Saved Games\ (no older files from older versions of RTTR) Sound-Converter.exe is crashing. The Ingamesound is terrible. 

Current "Workaround":  The old config from an old stable-build (not sure if it's Version 0.8.1) is ignoring this. (or seems to not start the sound-converter.exe)

This was tested with 3 Computers (1x Windows 7 64bit, 1x Windows 8.1 64bit, 1x Windows 10 64bit) on ALL Computers the Sound-Converter.exe is crashing.

**Comment by Flamefire** [comment]
Thanks for reporting. The bug is fixed with cc1c9183bb447182f003a91e3c1d646186a95d51 which will soon be available.
For the record: The bug originates in a 3rd party library we use, that seems to be outdated or has some issues with "recent" versions of windows compilers which results in files being opened with wrong permissions. Therefore future accesses to that file (from the same library) fail.
If the issue persists after updating to the newest version (20150914 or higher which will soon be available) please open a new issue and copy any output you have in the console
