### ISSUE TITLE
Game is crashing when leaving 

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#331]
this happens with every started game when quitting it. 
I am at a7c98d97e69b666d0b3fb61dd6d25e900c388d87 , because of #330 , so my apologies if it has been fixed in the meantime 

a backtrace, hope it is helpfull. 

client state changed to stop
server state changed to stop
s25client: /var/tmp/portage/games-strategy/s25rttr-9999-r2/work/s25rttr-9999/src/GameObject.cpp:103: virtual GameObject::~GameObject(): Assertion `!em || !em->ObjectHasEvents(this)' failed.
[New Thread 0x7fffeffad700 (LWP 27716)]

Program received signal SIGABRT, Aborted.
0x00007ffff62c0427 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff62c0427 in raise () from /lib64/libc.so.6
#1  0x00007ffff62c17aa in abort () from /lib64/libc.so.6
#2  0x00007ffff62b93dd in ?? () from /lib64/libc.so.6
#3  0x00007ffff62b9492 in __assert_fail () from /lib64/libc.so.6
#4  0x00000000004c2222 in ?? ()
#5  0x000000000071d2d0 in ?? ()
#6  0x000000000054f172 in ?? ()
#7  0x000000000054f3d6 in ?? ()
#8  0x00000000005368e5 in ?? ()
#9  0x000000000055615f in ?? ()
#10 0x00000000005b7543 in ?? ()
#11 0x000000000051f827 in ?? ()
#12 0x000000000056ceeb in ?? ()
#13 0x00007ffff28ded41 in VideoSDL::MessageLoop() ()
   from /usr/games/lib64/s25rttr/video/libvideoSDL.so
#14 0x00000000004d26cb in ?? ()
#15 0x000000000042449d in ?? ()
#16 0x00007ffff62ad7b0 in __libc_start_main () from /lib64/libc.so.6
#17 0x00000000004c1d39 in ?? ()
(gdb) continue
Continuing.
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.0.29/work/alsa-lib-1.0.29/src/pcm/pcm.c:7905:(snd_pcm_recover) underrun occurred
[Thread 0x7ffff7fc4780 (LWP 27712) exited]

Program terminated with signal SIGABRT, Aborted.
The program no longer exists.
(gdb) q

**Comment by Flamefire** [comment]
This is an unexpected side effect from 00e74cbb1a7e802c4236dbdb7dc52d8db54f5c28
I found that but fixed it only in a separate branch that contains various fixes for (more severe) problems. As this is only an assertion failure I did not consider it as urgent and tried to validate the other branch first so it could be merged. This is however not finished yet. I cherry-picked the commit to the current master so it should work now (6edb4e42a0a49dd1530b9fa4ecbaecc0c1aebca9)

Thanks for reporting. If you find anything else feel free to open issues for them (BTW: Well made issue. Took me only a few seconds to validate and handle due to your information and bt :+1: )
