### ISSUE TITLE
Soldiers won't go into tower even if there's space left

### ISSUE THREAD

**Issue by kyromaster** [Return-To-The-Roots/s25client#337]
Load the attached file. Then to the right, at the border to the red player there's a tower with only one soldier in it. And even if there's enough soldiers none of them will go into that tower :(
[bug wachturm.zip](https://github.com/Return-To-The-Roots/s25client/files/72695/bug.wachturm.zip)

**Comment by Flamefire** [comment]
Thanks for reporting. This bug is caused by a single soldier attacking and capturing a building. I have a fix in the works which even allows to "rescue" your savegame by detecting that invalid state. Once it is released this will get closed and you can test this. Easiest way of re-population the building will then be by adjusting the military settings once or probably by destroying the road and rebuilding it to trigger a search for soldiers.
