### ISSUE TITLE
Soldier waits and doesn't enter building

### ISSUE THREAD

**Issue by kyromaster** [Return-To-The-Roots/s25client#338]
In the attached savegame, if you look at the north-east, at the border to the red player, there's a barrack and one of my soldiers standing beside it. But he doesn't enter,
[bug baracke.zip](https://github.com/Return-To-The-Roots/s25client/files/72697/bug.baracke.zip)
 he just stands there. To free him I've to dismantle the barrack then he walks away.

**Comment by Flamefire** [comment]
Probably related to #335 which was fixed today. Using the new version will avoid the problem (although not fix the savegame itself as the soldier there seems to be in an invalid state) but I will check that.

**Comment by Flamefire** [comment]
Yes this was the issue previously fixed with 0b291b3ec70ffcaa4a3c6e41e4219a9e79c08c5e
Try using the latest version from today and this should not happen again. If it does, please report a new issue with a replay (although the save DOES help in identifying the issue, but the replay helps in finding HOW it happened)
