### ISSUE TITLE
Settlers gettings stuck (next to 1 node Water)

### ISSUE THREAD

**Issue by BlOedsin** [Return-To-The-Roots/s25client#354]
A minor bug, but especially with solders sometimes annoying (Similar things I already observed with solders )…  After building the road (see 2nd screenshot, they found their path)
Savegame: 
https://www.sendspace.com/filegroup/pKKn8VSeHkNV3TXXiUrxgg

![pathfinding_hunters - kopie](https://cloud.githubusercontent.com/assets/14259828/12221155/bd935bda-b78e-11e5-8bd6-968128965dfb.PNG)

![pathfinding_hunters2](https://cloud.githubusercontent.com/assets/14259828/12221149/8ade7a4e-b78e-11e5-9721-972ec6221e86.PNG)

**Comment by Spikeone** [comment]
II reported this issue long time ago (happens with roads over small 1 water node spots) - this affects all workers.

**Comment by Flamefire** [comment]
The bug is in the pathfinding code. When a node was already reached and is then reached from another node, then the reachability is not checked. In this case (top picture rightmost hunter): Pathfinding finds a path the the catapults flag (next to hunter) by going over the road above. It then expands the path: Left (to leftmost hunter), Left-Down and then checks Left-Up -> Finds the catapults flag again, sees the path is shorter and just takes it, ignoring that it can't reach the node from the current node. It basically assumed that if a node is reachable from 1 node, it is reachable from any node, which is clearly wrong.

This bug can be fixed after #360 is merged, as that PR changes the pathfinding system.

**Comment by Spikeone** [comment]
You are right, I forgot that if each node is bwater then it's like one meadow. I also forgot that even f bwater would only allow flags, the map wouldn't work anymore as I'm using the mechanic that 1 node water can be passed if a road is built and not if there is no road.
