### ISSUE TITLE
 Ki builds no donkey breeds

### ISSUE THREAD

**Issue by Strawberry93** [Return-To-The-Roots/s25client#380]
Ki builds no donkey breeds and have many problems with their transport ways.

**Comment by ikharbeq** [comment]
Cannot confirm: For me the AI does build a donkey breeder when it is supposed to build one.

Just tested this in current nightly on the map Big Slaughter v2 by Vesanus with 7 AI players. Jumped to gf 100k  and when I checked 7 out of 7 AI players had a donkey breeder. The construction rule is in https://github.com/Return-To-The-Roots/s25client/blob/master/src/ai/AIConstruction.cpp: AI needs more than 2 pickaxe + miners and more than 7 farms.   
When adjusting theses values we should be careful because when the AI does not get 8 farms or the 3 miners+pickaxes either space or resources are probably at least somewhat limited and getting donkeys  really has to be more relevant than more food or buildings that cost stones.

**Comment by BlOedsin** [comment]
I checked in my game as well. I am not sure if they started building donkey breeding (7 farms are there), as they were totally out of wood. They only have one forester and two woodcutter but 3 sawmills. Is that normal? is the assumption that they find more wood on the map itself?

![ki production](https://cloud.githubusercontent.com/assets/14259828/12701368/461353d2-c808-11e5-8e0c-8fa2f46c1cfb.PNG)
![ki production2](https://cloud.githubusercontent.com/assets/14259828/12701369/47d8af0a-c808-11e5-88f5-cf80509cf2f6.PNG)

**Comment by ikharbeq** [comment]
2-3 sawmills is correct for the start (depending on start resources) and should scale with woodcutter count/2 above that.  
The ai currently has no check: much space and no trees: make more foresters just one for: many woodcutters? (which requires: many trees) -> skip foresters. So for now: yes the ai kinda expects at least some trees on the map but there should  be a 2nd forester soon (military buildings / 6 + 1) but probably no lumber remains to construct it in the situation in your screenshot... 
Try jumping (j) 50k+ gf and check if the ai got over the bad start situation.

**Comment by BlOedsin** [comment]
Yes after some time it was built, you are right! Not at a place were I would have done it, but it built.
In the situation with just one forester, I counted 10 military buildings.... But the 2nd forester was already in construction....
Nevertheless, building so many farms, before a 2nd forester is a bit strange to me....

Regarding lumber: I started for sure with goods to start = normal, so there would have been for sure enough resources to build more than that…. 

![bad situation](https://cloud.githubusercontent.com/assets/14259828/12701825/cf4d4a50-c816-11e5-8d13-9082143031c1.PNG)

**Comment by jhkl** [comment]
I increased the number of foresters/woodcutters two days ago. Also relaxed some of the placement constraints.

**Comment by BlOedsin** [comment]
In my last game yesterday, I had the feeling, that KI is not attacking at all. Can you double check, if that is maybe a side effect of your other changes? 
Even in Ta quick test on the map Tot-Ecke against strong and medium KI, I was not attacked a single time!

**Comment by jhkl** [comment]
For better overview, I put that into another issue: #384
