### ISSUE TITLE
Game crashes reproducibly

### ISSUE THREAD

**Issue by mplatt** [Return-To-The-Roots/s25client#4]
To debug this load the game and burn down the guardhouse located on the border of the white player. The game will crash.

Savegame + Replay + Log available at: https://drive.google.com/folderview?id=0B-w61I34QpTgflc4MUlTcENibURGMkRWVm9PQlU5U3Rmel84QXVONnNVNGZQRTFSNW1UMTQ&usp=sharing

**Comment by jhkl** [comment]
This is caused by territory calculation for the destroyed military building: The other non-occupied military buildings in range are destroyed as well, which triggers a search for the other player's military building looking for nearby enemy military buildings. This search finds the military building that was just manually destroyed by the player.

Fix should be the earlier removal of the destroyed military building of the list of military buildings.
