### ISSUE TITLE
s25update.exe downloads files to the wrong location

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#434]
The normale folder structure is:

./RTTR
./Worlds
./DATA
./GFX
./driver

the s25update.exe is located in ./RTTR/s25update.exe

When you start an update, the s25update.exe starts downloading RTTR to it's own location but should be ../ instead.

So you end up with
./RTTR
./RTTR/RTTR
./RTTR/driver
./DATA
./GFX
./driver

As the rttr.bat tells me, the correct calling would be with parameters, "RTTR\s25update.exe --dir %CD%" - but why is that? It's okay for me to tell an updater where to download it and use the current location if no path is provided but... why don't we put the s25update.exe to the same folder as the s25client.exe? I know there are some .dll dependencies but IMHO it's still worth getting rid of a .bat file just to call the s25update.exe with correct parameters (or tell at least, that --dir should be provided instead of calling the .exe)

**Comment by Flamefire** [comment]
So executing s25update.exe directly downloads to wrong location, but executing via the batch script works correctly? Then one could at least make sure, s25update.exe tries to find the correct path itself, if directly called.
I also don't see a problem with the updater in the subdirectory. We can assume/check this and still download to correct location. However the problem is the different folder structure between OSes which I don't quite understand. If anyhow possible, I'd like to have the same on all OSes so we can be sure, where our files are, independent of the OS. See #257
