### ISSUE TITLE
compiling issue

### ISSUE THREAD

**Issue by ghost** [Return-To-The-Roots/s25client#5]
-- Could NOT find SDL (missing:  SDL_LIBRARY) (found version "1.2.15")
CMake Warning at driver/video/SDL/src/CMakeLists.txt:38 (MESSAGE):
  : SDL library not found: Not building SDL videodriver

-- Could NOT find SDL (missing:  SDL_LIBRARY) (found version "1.2.15")
-- Could NOT find SDL_mixer (missing:  SDL_MIXER_LIBRARIES) (found version "1.2.12")
CMake Warning at driver/audio/SDL/src/CMakeLists.txt:45 (MESSAGE):
  : SDL library not found: Not building SDL audiodriver

CMake Error at mygettext/src/CMakeLists.txt:8 (MESSAGE):
  libiconv not found

and using cmake-gui
CMake Error at cmake/crosscompile.cmake:57 (MESSAGE):
  ERROR: -dumpmachine failed...  Result:'No such file or directory' Error:''
  Output:''
Call Stack (most recent call first):
  CMakeLists.txt:22 (INCLUDE)

**Comment by kumzugloom** [comment]
Hi ghost,
I'm not an expert at all, but you are providing pretty few information. What system are you trying to compile, what ist your setup, etc.

Still, I had a lot issues in compiling, but found some help. I guess, this issue https://github.com/Return-To-The-Roots/s25client/issues/1 I opened earlier, could therefore help you.

**Comment by fguzm** [comment]
Debian testing 64 bit, issue due to wrong cmake version, i think - Now solved, but:
I run into another compiling error.
make[2]: *** No rule to make target '/usr/lib/liblua.so', needed by 'src/s25client'.  Stop.
CMakeFiles/Makefile2:1188: recipe for target 'src/CMakeFiles/s25client.dir/all' failed
make[1]: *** [src/CMakeFiles/s25client.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
There is no file /usr/lib/liblua.so on 64 bit debian. I have a file called liblua5.2.a under /usr/lib/x86_64-linux-gnu. Odd enough, cmake-gui states the following before:
'Checking LUA library at /liblua52.a
Using LUA library from /usr/lib/liblua.so
Configuring done'

**Comment by Flamefire** [comment]
This should work when setting CMAKE_PREFIX_PATH to /usr/lib/x86_64-linux-gnu
Like: ./cmake.sh --prefix=. -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu

**Comment by Flamefire** [comment]
Can be closed
