### ISSUE TITLE
MissionStatement(player, title, message) visual "bugs"

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#521]
I think LUA scripting can be considered as implemented, so I can finally also report bugs.

The MissionStatement windows just looks... odd.

 Window has minimize buttons => should not have those
- [ ] Continue button is to big
- [ ] Continue button has wrong texture  => 7 current, 1 origina
- [ ] background has wrong texture => 7 current, 5 original
- [ ] Statement closed on rightclick
- [ ] Game cant be paused upon opening
original:
![original](https://cloud.githubusercontent.com/assets/1276342/17151779/2cb6f756-5375-11e6-8702-3b0b7b0b9cdf.png)

rttr:
![rttr](https://cloud.githubusercontent.com/assets/1276342/17151785/320d24d2-5375-11e6-974c-bdc2f3617e7b.png)

**Comment by MarcusSt** [comment]
The signature should be changed to MissionStatement(player, title, message, task), where
- message: long message shown in mission statement window
- task: short summary for mission diary (needs to be implemented, see #522)

**Comment by lvanderwall** [comment]
@Spikeone  Please add "5) Window should not close on rightclick " to your list above. In the original game, mission statements do _not_ close on rightclick as most other windows do! I really think that makes sense, as you could accidentally close mission statements that way.

**Comment by Spikeone** [comment]
@MarcusSt I'd rather like to have a seperate function as I mission statement may doesn't need to update the task and the other way round.

**Comment by Flamefire** [comment]
If the mission statement does not need to update the task, then nil can be passed. But you should not be able to update the task w/o a mission statement.

**Comment by Spikeone** [comment]
Why? Mission statement tells you to build a basic economy - you may check if woodcutter, sawmills are built and check the task accordingly.

First the task says "build a basic economy"
When a sawmill is built you may update it to "build a woodcutter and forester"
And after a forester is built you may update it to "build a woodcutter"

Why should I be forced to always show a statement? Task is more like a help and might not be related to the statement.

**Comment by Flamefire** [comment]
Ok, right you could show progress in the task. E.g. for "Collect 100 wood" you can show how many was collected.
So lets do both: MissionStatement receives an optional task param which is passed to the new function `setCurrentTask` but that function can also be called manually.
How shall we store the current task? We currently don't have that. I'd store it with the GamePlayer and also save it to the savegame. If you use it in multiplayer you have to make sure to save it yourself or set the task for all players, not only the local player. Otherwise we need to synchronize it.

**Comment by Spikeone** [comment]
Sounds okay for me - even if one needs to save the statement on his own that'd be okay IMO (ie organize your tasks in an array and only save the index and set the task on load)

But as it doesn't matter - do it the way you like it :)

**Comment by lvanderwall** [comment]
Instead of saving the current mission _state_ I'd save the _history_ of all events successfully called. On loading, you set buildings / messages / event states to their initial values and call all events of the saved history in order, only without mission statements. That will set the right task automatically and enables / disables the right buildings. It works fine even if some events enable / disable the same buildings.

Otherwise, disabled / enabled buildings would have to be saved separately as well as the event state. In the Roman Campaign I only save the indices of all successfully called events (that's not much, < 20 int s for mission I, by far the largest script), and call those events on load to enable/disable buildings and update to the correct mission state.

**Comment by Flamefire** [comment]
This is possible: Instead of saving the state you save the history and replay it (like savegame vs replay). This does however break if you show mission texts or other messages in the events unless you handle that specifically.
Note that for multiplayer missions this might get a bit more complicated. We also should state, what we save and what we don't save. See #556

**Comment by lvanderwall** [comment]
In the Roman Campaign I solved the problem of the messages (and adding resources for that matter) by having an `onLoad` parameter next to the event index `e`:
```
function MissionEvent(e, onLoad)
    if(e == 1) and not onLoad then
        ... // e.g. message text for event 99, update event history
    end
end
```

That may work here as well.
