### ISSUE TITLE
Military options

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#541]
In RttR we have 1/8 steps for each military indicator, S2 we hade 1/10 steps for each. 
That way in S2 a watchtower was occupied with 1 soldier if you kept default settings, in RttR it's occupied with 2 soldiers.

![colors](https://cloud.githubusercontent.com/assets/1276342/17269643/7c28f326-564e-11e6-899f-e4d018e26d16.png)

RttR: 10, 5, 5, 5, 8, 8, 8, 8
S2: 10, 4, 4, 4, 10, x, 10, 10

Note: This is just a bug to keep track of it, I think it'd be enough to decrease the "inland" bar to 12.5% instead of 25% to have the same behavior as we had in the original.

**Comment by Flamefire** [comment]
The color is also to bright... Still: This should be the same as S2

**Comment by Spikeone** [comment]
Well, I may remember that we have changed that because this way (1/8 steps) you have the best control over a fortress, with 1/10 you don't. Which is an improvement I guess.

**Comment by Flamefire** [comment]
Ok. But there is still a bug: We have not 8 steps but 9: 0-8
I also observed the behaviour in S2 and it was different than what we use.

![s2mili](https://cloud.githubusercontent.com/assets/309017/17494496/3b8cf65a-5db5-11e6-9753-75a81ee2a074.png)

So my suggestion: We use the 9 steps from S2 that are useful (skip 0 and 1). Or come up with something better. Using 8 Steps only because it corresponds to the fortress would raise critics why it does not work for towers. And currently the 9 steps are also kinda pointless as 0 and 1 are the same.

So what shall it be? The 9 steps from S2? Would be best as it keeps the old behaviour while it also fixes the bug with the first to steps

ccing @Flow86
