### ISSUE TITLE
Possible "Singleplayer -> Campaign" - Screen

### ISSUE THREAD

**Issue by lvanderwall** [Return-To-The-Roots/s25client#568]
I've been thinking about the "Singleplayer -> Campaign" screen that's not yet implemented, and how to improve the original one from S2. I know it's something for the distant future, so it's just a brainstorming to collect a few ideas:

![campaign_screen](https://cloud.githubusercontent.com/assets/16540971/17620971/8c24c2f4-6090-11e6-8e4c-d4ab8319568d.png)
- [ ] campaign screen lists all missions for that campaign. Missions you can't play are disabled / grayed out
- [ ] improvement to S2: A "Campaign-Dropdown" that lists all campaigns you have installed in the campaign folder (see below)
- [ ] don't show map overview on start, at least in single player mode

Store new campaigns (and possibly the campaign progress) in a separate subfolder. People shouldn't need to copy new campaign files into the `DATA` folder like in the original:
- [ ]  all `swd`\- and `lua`-files for a campaign "MyPaign" are stored in a subfolder `%RTTR_INSTALL%/RTTR/MAPS/CAMPAIGNS/MYPAIGN`
- [ ] save campaign progress, possibly by a `mission.dat` that is stored in the same folder
- [ ] enable new missions by a lua command `ActivateMission(i)`
- [ ] for the "Roman Campaign" there should be a `readme` to inform people which map files to copy into the folder, as those maps cannot be included included directly for copyright reasons

As I said before, it's just a brainstorming to collect some ideas, so feel free to add to them or crush them completely!

**Comment by Spikeone** [comment]
Damn - gonna edit this post when I'm home

**Comment by Flamefire** [comment]
We can store the campaign progress (which mission is next) in the general settings file. Avoids problems if the maps directory is not writable. 
The masterfile must be designed carefully. What do we really need? 

1. Name
1. Description 
2. Author
3. Map file names or shall we use a clever naming? Maybe both: map names must be same as masterfile but with _m1-9 attached and the master must state the number of missions so we can detect missing ones. 

Anything else? 
Translations are hard. Maybe make ini files with "[Name]" as the section and entries for each language? Map names are even harder because I'd take the name from the map file to keep it consistent with the preview/join screen. But no translations there yet. 
I would allow subdirs but don't require them. 

I like the old mission screen. Why not keep it for mission selection and add a list (similar to map list) before that to select a campaign which is skipped if there only is one?

We can add a campaign mode (need to store the campaign name anyway for enabling the next mission from Lua) so the map preview is not displayed or we can add a Lua function to remove the map preview. I'd go with the latter.

**Comment by Spikeone** [comment]
While working a bit on the old campaign I was thinking about this topic and the screen.

First of all, I don't think this screen should be for singleplayer only, we might add a multiplayer campaign some day.

For selecting a campaign, one could use the selection of maps screen, but rather than showing maps we should show campaign definitions. I don't think that there should be a preview or description or something like that, although those would be nice additions, they aren't nedded in my opinion.

Once you selected your campaign, you get a map selection as shown above (so more like the original). I'd still switch to the host screen then, on one hand to enable checking settings (custom campaigns) and on the the other to make multiplayer campaigns possible.

The campaign definition file doesn't need much, it's simply the name of the campaign, author, player (so 1 for singleplayer) and a list of maps in order. I don't think we need some fancy decision making (e.g. if you defeat player a) your next mission is 3b, if you defeat player b) your next mission is 3a) so it's simplay a list.
In the rttr settings file we should simply store which map has been unlocked (I think much like the original simply 0 or 1 so users can 'cheat').

**Comment by Flow86** [comment]
I think we could do it like that:
Add a directory "campaigns" where each folder is a campaign. The folder also contains a description file (i.e ini file with description, author, player count, preview image?), the maps and the lua campaign files. Then we show it like the maps selection for Single- and Multiplayer.

What do you think?

**Comment by ottml** [comment]
I would like to implement the campaign screen and the logic behind. I tried out the following gui workflow. It would be nice to have a further dicussion whats the best gui workflow for the campaings. Feedback, suggestions and further ideas for the gui workflow are very welcome.

On the single player screen activate the new "Campaigns" button
![singleplayerscreen](https://user-images.githubusercontent.com/33401986/235258819-3c8f342c-e3a2-4813-b01f-94c34ceabd0e.png)
After clicking the button the single player map choose screen opens with the new "Campaigns" entry preselected. The table shows all available campaigns with some additional information as suggested in previous comments.
<img width="1920" alt="chooseCampaign" src="https://user-images.githubusercontent.com/33401986/235258844-9760fd26-7f11-4a8e-be84-07c9ad4771c2.PNG">
The user can then select one entry within the campaign table. After selection the missions of the campaign are shown. By clicking on a mission the next screen for starting the selected mission is opened.
<img width="1920" alt="selectedcampaign" src="https://user-images.githubusercontent.com/33401986/235258854-fc0858a0-ffa0-4ef8-91cd-a0dd9cab8247.PNG">

**Comment by Spikeone** [comment]
First of all, our minimum supported resolution is 1024x768 as far as I remember - one has to always keep that in mind.

Second we need to support 1-n campaign maps which one just needs to consider.

For that reason I'd keep it pretty simple:
Use the normal mapscreen layout (just like you did) for campaign selection. After clicking "continue" you jump to the mission selection screen where maybe on top a description is shown (we still need to add some mission.lua file or something alike that has a maporder, possibly an identifier, a description and maybe other things) and below all maps in a 10xN layout where you can scroll (button) throug pages (if more than 10 missions are part of the campaign).

As reference the 1024x768 Screen:
![grafik](https://user-images.githubusercontent.com/1276342/235291962-2aa47081-db26-4a63-9ed3-6c0e61b33550.png)

**Comment by ottml** [comment]
Ok the minimum resolution is a good hint. I put it on one page to not have to switch back to select an other campaign and see it's mission. But yes if we have space limitation it's the better and cleaner solution to put it on a separate page.
<img width="505" alt="campaign_one_screen" src="https://user-images.githubusercontent.com/33401986/235979704-ad46709b-b612-4c8a-9205-e00c5b1b67e7.PNG">
<img width="505" alt="campaign_missions" src="https://user-images.githubusercontent.com/33401986/235979708-4168617a-071f-4e17-afac-10042e3a0b50.PNG">
A first draft for discussion can be seen in the images attached.

**Comment by Spikeone** [comment]
I like this idea, although I think having space for a campaign description would be nice.

The page switches might be something like:
![grafik](https://user-images.githubusercontent.com/1276342/236005668-a826f36e-8bdf-46e4-a0c9-6a4fd949f730.png)

On larger resolutions we could use two columns.

**Comment by Spikeone** [comment]
I pretty much like this version (although a page number of 2 seems wrong for 10 missions).

You mind having a draft where on the left side the missions are displayed and on the right side the description text is displayed?

Something like this I'm thinking about:
![grafik](https://github.com/Return-To-The-Roots/s25client/assets/1276342/6b6e679c-a720-4ccd-8dca-3217d4851bd0)

**Comment by ottml** [comment]
Your suggestion can look something like this:
![mission_descriptio_on_side](https://github.com/Return-To-The-Roots/s25client/assets/33401986/8628f8c0-8656-4d2b-99e3-97e7427b01a9)
But after some experiments i would suggest a two widget approach. Like in the following screenshots:
![two_screen_campaing_selection](https://github.com/Return-To-The-Roots/s25client/assets/33401986/ace97387-a9dc-49c1-b760-32a48f788b3d)
![two_screens1](https://github.com/Return-To-The-Roots/s25client/assets/33401986/ba5e7743-87c5-4eaa-8717-38c29d20cb50)

So you have at the first screen the campaing description onces and not using a lot of space on the mission selection page which is not needed there becaue it's the same for all missions nevertheless. This has also the advantage of a clearer user interface. The user is able to choose the campaign and if he has finished one campaing we are also able to select the next campaign automatically, so the user must not go to the mission selection page every time but can easily click the play capitel button.

**Comment by Spikeone** [comment]
I honestly liked the first screenshot quite a lot.

In the campaign selection screen I'd rather use a select-switch-button. Which means you click on the button, the button stays clicked, the description is shown, you can click on continue to play that campaign.

So in my game it's like (which pretty much uses buttons which are settlers2-ish): 
![grafik](https://github.com/Return-To-The-Roots/s25client/assets/1276342/76344d34-f2a8-4a05-b83c-f700e5c867b2)

**Comment by ottml** [comment]
I added three drafts for campaign selection. The three gui's and workflows can be triggere using the button marked in the screen shot. 
![grafik](https://github.com/Return-To-The-Roots/s25client/assets/33401986/57a9e636-890c-414e-bcba-dd77bbc87799)

1. Table of campaigns with minimal description. Clicking on campaign opens a new screen with the avalaible missions.
2. Table of campaigns with minimal description. Clicking on campaign opens a new screen with long description of the campaign. And the possibility to go to another screen to select the mission to play. Or directly play the prechoosen mission.
3. List of campaigns with advanced description beside (like suggest by @Spikeone). Clicking on campaign opens a new screen with the avalaible missions.

**Comment by ottml** [comment]
This is no final implementation but only a draft to see the different concepts of campaign selection and try it out which workflow is the best one for the final implementation. Therefore some thinks are not implemented completly and the gui's are only an early draft, which were easy to code.

It would be nice if you can play around with the different workflows and give your feedback how we want proceed and in which direction we will go for the final solution foe campaign selection. @Flamefire @Flow86 @Spikeone @lvanderwall
