### ISSUE TITLE
Make a Brickmaker

### ISSUE THREAD

**Issue by geojak** [Return-To-The-Roots/s25client#621]
like the coal maker one could add a brick maker building for late game when stones tunes out.

It would need to be build next to sand.
Worker needs a shovel and get sand, then he needs wood, water and coal and would burn some bricks aka stones.

**Comment by geojak** [comment]
If we then could find a way to get acces to iron and gold after mines have run out it would be set. I suggest a way similar to s3.
New temple building: supply it with lots of fish/meat/breed and get random small amount of gold/metal

**Comment by Spikeone** [comment]
Well, there are already inexhaustible granite mines as addon (which I guess already solve your stoneproblem?).
Also I don't think temples should be used for such things as generating resources.
What about using a... don't know a name but a building that needs stone + food and then produces iron, either after x-work cycles or only if 6food and 6stone are provided.

It needs to be more expensive than normal mining (just as the charburner).

**Comment by geojak** [comment]
The thing with the unlimited mines is, that they will run on 100% forever. There is no need to ever expand your mining area and squeeze all out of a given mountain.

Once I have 1 granite mine, maybe 2 I am basically set for the hole game.

By introducing a brick maker, it would still be favorable to get the cheap stone out of the mines because bricks are expensive to make and takes very long

Similar arguments should hold for iron. 
I thought about a temple becaus I don't see anyway of "making" iron without divine intervention

**Comment by Spikeone** [comment]
Well, same applies for temples then - if I have a flat region where I can build a lot of farms but I do not hold any mountain, I could still fight a player who fought for mountains but has no farmland (because he fought for mountains). 
It's quite similar.
Also I'm only talking about inexhaustible granite mines, not inexhaustible mines.

Means:
Farmer -> Carrier -> Miller -> Carrier -> Bakery -> Carrier -> Stone Mine -> Carrier -> Stonecrusher
Which is a quite long production chain. Could also involve coal (e.g. melt those stones, sometimes you get iron or gold, sometimes not). 

still more favorable I think as it is quite logic.

"We do not have easy access to ore anymore, now we have to work harder to get ore" (by crushing stones more often).

**Comment by geojak** [comment]
I See. That sounds quite reasonable. 

With the stone crusher and brick maker it just needs to be always a lot worse than just mining (as long as you can), while still allowing military production once everything is depleted, so the player with most land (actually farm land) would be in favour.

**Comment by geojak** [comment]
How about an addon that gives depleted mines a 5% chance to still find something

**Comment by Spikeone** [comment]
As the last comment was a wish for another addon - I'd close this one for now.
