### ISSUE TITLE
AI stuck

### ISSUE THREAD

**Issue by luk3ZPL** [Return-To-The-Roots/s25client#674]
AI stopped build any building (stuck) when there is no suitable place for it (probably from AI priority list).

1) Which version is affected?
	20170811

2) What did you do/shall be done to reproduce the bug?
	Look at AI red player from save (again this AI have really bad luck ;) :
	http://www.mediafire.com/file/1iq0agqmc9tw1mb/AI_bug.7z

3) What is expected? (Unless it is a crash)
	AI should expand borders a little bit (at the begining of the game when is isolated) to find a suitable place for building.
	
4) What happens instead?
	AI stopped build any building (stuck).

**Comment by Flamefire** [comment]
Some analysis: This is caused by an unfair map created by the mapgenerator from @vader1986 (you may want to look into this)
The red player has only hut building qualities so he cannot build a sawmill. This is currently the condition for expansion for the AI written by @jhkl (any ideas?) I might have an idea how to fix this by simply removing the condition that checks for planned or built sawmills. Reasoning: The AI will try to build a sawmill first. So if it isn't planned or in the construction queue then it is impossible and the AI should expand to try somewhere else. However the AI currently tries to build only around warehouses. Maybe it should try somewhere else if this fails to find a space?

**Comment by luk3ZPL** [comment]
Any workaround will be good.

**Comment by jhkl** [comment]
Expansion sounds like a valid fallback if nothing else works ;)
I think it tries to build around random military buildings as well (if there are any).

**Comment by vader1986** [comment]
@flamefire: I'll probably go for some bugfixes/map generation improvements around Christmas. Really sorry, but I'm quite busy and have no internet connection at home.

**Comment by frin** [comment]
I managed to fix the AI problem, tested on this case in particular, PR https://github.com/Return-To-The-Roots/s25client/pull/682. I've detailed the change in the PR comment. Once the AI builds the first military building it spreads well, building sawmill and other buildings.

The problem was that there were no build tiles suitable to build a sawmill within initial border.
![screen shot 2017-08-25 at 19 25 55](https://user-images.githubusercontent.com/176282/29727065-ab5b4bf4-89d2-11e7-99b0-b8feedc580b3.png)
