### ISSUE TITLE
CMake install path handling is broken

### ISSUE THREAD

**Issue by hasufell** [Return-To-The-Roots/s25client#692]
On linux:
```
CMake Error at CMakeLists.txt:195 (message):
  All RTTR_*DIR variables must be relative paths.  RTTR_BINDIR is absolute:
  /usr/x86_64-pc-linux-gnu/bin
```

This is **not** how `GNUInstallDirs.cmake` is supposed to be used and it breaks distro support.

**Comment by Flow86** [comment]
you're right, the path handling is still wip, since we need some tradeoff between being standard conform and handling multiple platforms and or portable installation support.

Perhaps you have an idea/proposal how we could do that better then currently?

**Comment by hasufell** [comment]
I don't see how disallowing absolute paths is required to handle multiple platforms.

**Comment by Flow86** [comment]
yea you're right, I think thats only a failsafe "error" so that the nightly builds can't be wrongly built.

**Comment by Flamefire** [comment]
No it is there for a reason. See my description in the wiki: https://github.com/Return-To-The-Roots/s25client/wiki/Folder-structure-and-RTTR_*DIR-config-variables
Point is: all paths have to be relativ to the install prefix so we can find this install prefix and from there find all files.
Only solution I can think off: allow absolute paths which means a non-portable version. In the client we skip the prefix path handling for absolute paths. Not sure if this might not break to at some point...
Maybe even make a flag in cmake to set portable or not and then check and or enforce the absolute or relative paths.

@hasufell: why is the path absolute in your case? I thought the gnuinstalldirs only return relative paths unless especially requested

**Comment by hasufell** [comment]
> Point is: all paths have to be relativ to the install prefix so we can find this install prefix and from there find all files.

That's not good. In order to find files you should have a proper logic that first checks for compile-time configuration of paths and then falls back to something else (e.g. to support portabel installs). GNUInstallDirs has expanded variables for exactly that purpose: `CMAKE_INSTALL_FULL_<dir>` (always absolute), which you can pass to the preprocessor, without relying on the prefix at all.

> Maybe even make a flag in cmake to set portable or not and then check and or enforce the absolute or relative paths

Possible. Still, you shouldn't assume anything about prefixes for non-portable installs. It won't work on all filesystem layouts.

You cannot assume that the prefix is the same as the destination of the data files.

> why is the path absolute in your case? I thought the gnuinstalldirs only return relative paths unless especially requested

No. `CMAKE_INSTALL_<dir>` may or may not be absolute, it can be both. `CMAKE_INSTALL_FULL_<dir>` is always absolute and often used for the preprocessor.

Don't rely on the prefix.

**Comment by Flamefire** [comment]
Ok I think we can simply add a cmake bool for portable installs that makes it work like it is atm. If false then we enforce absolute paths (except for Windows. What about Mac? Don't know how those packages work but I think they need relative paths too)
A non-portable configuration could not be executed from the build directly due to that. It needs to be installed first.

Any issues with that? A portable install will always have a prefix so this cannot fail.

How else could we solve that?
Only idea from me: Use special markers in the paths like "<LIBDIR>/drivers" and relay those through a function which replaces them by the configured RTTR_LIBDIR. In a startup phase it could check if the path exists and if not replace the configured path with a hard-coded portable path (maybe from cmake RTTR_LIBDIR_PORT to make even this configurable) this would allow to use the absolute paths from gnuinstalldir in all cases and remove the need for a portable flag.
We could go even further and add common build paths to the list of paths tried.
However we would still need to find the prefix path from within the executable like we do currently. And it will fail if the absolute install dir exists but is not used like in a portable install that is moved.
This brings me back to the need of a portable flag which switches between absolute and relative paths. 

The relay function might still be a good idea to allow execution from the build dir (not installed yet) if we could somehow detect this reliably.

**Comment by Flamefire** [comment]
Coming back to this. I found https://redmine.malikania.fr/news/35 where it says 'It is highly recommended to make relocatable software. Using absolute paths would break this.'

But I want to understand your point/use case, @hasufell . I guess you, at some point, call `cmake -D CMAKE_INSTALL_BINDIR=/usr/x86_64-pc-linux-gnu/bin ...` which is why the path ends up being absolute. Is this correct?   
What exactly is the problem with relative paths? You say 'You cannot assume that the prefix is the same as the destination of the data files.' Why? Isn't that exactly what happens on a `make install`? That all files are installed into `${DESTDIR}${CMAKE_PREFIX_PATH}/<someDir>` so that if <someDir>is stored in the binary I can get up to the actual prefix? When can this break?

This is for my understanding only as I have seen this in the very same project I referenced above: https://redmine.malikania.fr/projects/irccd/repository/entry/libcommon/irccd/system.cpp#L327

So I would implement the same behavior: If absolute paths are used, they are used as-is. For relative paths we still do our "magic" with the prefix path. That is:

If RTTR_BINDIR is absolute the prefix path is CMAKE_INSTALL_PREFIX, else it is the path from which RTTR_BINDIR can be found, which is a parent directory of the executables path.

If RTTR_<SOME>DIR is absolute, it is taken as-is. If it is relative it will be relative to the prefix path as defined above.

The build directory mimics the install directory which is always possible on linux but we still disallow absolute paths on windows unless we want to implement some more logic for building.

Side note especially for @hasufell I guess you are not using/building the updater? I'll add a RTTR_BUILD_UPDATER to CMake to cover this. @Flow86 We might even disable this as soon as non-default paths are used (e.g. any absolute path would force-disable the updater)

Comments?

**Comment by hasufell** [comment]
> 'It is highly recommended to make relocatable software. Using absolute paths would break this.'

Distributions don't care about relocatable software. They install into a pre-defined filesystem layout and need full control over __all__ destination directories.

What you do with your portable installation logic is orthogonal. But as you can see, it doesn't work for both, because the assumptions about prefixes are wrong.

> I guess you, at some point, call cmake -D CMAKE_INSTALL_BINDIR=/usr/x86_64-pc-linux-gnu/bin ... which is why the path ends up being absolute. Is this correct?

Yes and that is __expected__ behavior.

> What exactly is the problem with relative paths?

They don't fit our filesystem layout. Data files have a __different__ prefix than binary/library/include files on some distros due to e.g. multiarch. It will be even worse on distros like NixOS, which completely break all your FHS expectations. Really, all of it.

> 'You cannot assume that the prefix is the same as the destination of the data files.' Why? Isn't that exactly what happens on a make install? That all files are installed into ${DESTDIR}${CMAKE_PREFIX_PATH}/<someDir> so that if is stored in the binary I can get up to the actual prefix? When can this break?

No. `${CMAKE_INSTALL_PREFIX}` is ignored if you pass `-DCMAKE_INSTALL_BINDIR=/some/absolute/path -DCMAKE_INSTALL_DATADIR=/a/completely/different/prefix`.

> If absolute paths are used, they are used as-is.

As it should be.

**Comment by Flamefire** [comment]
Ok thank you for that. I'll create another PR implementing this behaviour soon.
Would you be willing to participate in the review of that PR to assure I did not miss anything? If so, I'd CC you and wait for your comment before merging.

**Comment by stefson** [comment]
at current git I get this in configure: 

```-- Using platform config cmake/linux.cmake
-- Linking against boost dynamic libraries
-- Boost version: 1.62.0
-- Boost 106200 detected. No backport required
CMake Error at CMakeLists.txt:241 (message):
  All RTTR_*DIR variables must be relative paths.  RTTR_GAMEDIR is absolute:
  ~/.s25rttr/S2


-- Configuring incomplete, errors occurred!

**Comment by Flamefire** [comment]
Same issue. Will be resolved with the path system rework.

**Comment by stefson** [comment]
ok, ping me if you need testing

**Comment by stefson** [comment]
I just noted that my ebuild script does set a relative path itself for -DRTTR_GAMESDIR. 

Which values for -DRTTR_GAMEDIR are now acceptable, in case you would like to have the GAMEDIR as before in ~/.s25rttr/S2 ? Or would you like to see them rather somewhere in /usr/share ?

**Comment by Flamefire** [comment]
There is a default based on gnuinstalldirs which we use. Probably a subfolder in /usr/share

**Comment by Flamefire** [comment]
Added PR to fix this. See #707

**Comment by stefson** [comment]
almost there :-) compiles, installs, only problem left is the RTTR_GAMESDIR variable (?) - the binary wants to load the graphics from the original release from share/s25rttr/S2/ ; this propably means it expects to find them in a place which is /usr/bin/share/s25rttr/S2. Is this how you would like to see it? 

And is it still possible to set RTTR_GAMESDIR to ~/.s25rttr/S2?

**Comment by hasufell** [comment]
> And is it still possible to set RTTR_GAMESDIR to ~/.s25rttr/S2?

That was a quick and easy hack, but you shouldn't do that. Judging from FHS the appropriate place is indeed [/usr/share/games](http://www.pathname.com/fhs/pub/fhs-2.3.html#USRSHAREARCHITECTUREINDEPENDENTDATA), however you could also hijack [/var/games](http://www.pathname.com/fhs/pub/fhs-2.3.html#VARGAMESVARIABLEGAMEDATA) for that, given that the PM cannot install those files. The raw static data files are not something that makes sense to install per-user.

**Comment by Flamefire** [comment]
Yes the default path is share/s25rttr/S2 but it can be changed.
After @hasufell comments we could also use share/games/S2 for that which sounds appropriate.

Seeing /var/games I think we should even store the replays etc. in /var/games/s25rttr and move our other static files also to share/games/s25rttr instead of share/s25rttr by default. The link mentions that `static game data must be stored elsewhere`. So I wouldn't place the S2 data there.
We could even put the libs in libs/games/s25rttr but I think this is to much. Even the link above mentions that as optional.

What do you think? ccing @Flow86 @hasufell @MarcusSt

**Comment by hasufell** [comment]
> we could also use share/games/S2 for that which sounds appropriate

`/usr/share/games` vs `/usr/share` is really not an important decision. Both are fine, some distros prefer one over the other, they can chose whatever they want.

> Seeing /var/games I think we should even store the replays etc.

Some people won't like that, because then it's basically shared between users. As a default it could make sense, but opting for users home dir should still be possible for variable game data. If you don't want to allow odd paths like `~/.s25rttr/S2`, make a [cmake_dependent_option](https://cmake.org/cmake/help/latest/module/CMakeDependentOption.html): if someone doesn't want user-home directory, he must specify a path.

**Comment by Flamefire** [comment]
True, especially the sharing would be bad. Then I'd keep it like it is so we don't change the existing structure.

Therefore the PR is ready for merging. I'll also change the documentation in the wiki after it was merged. We do cheat a little bit with the path handling. We simply change the working directory to the prefix path which is either the parent directory of `RTTR_BINDIR` or `CMAKE_INSTALL_PREFIX` if the former is absolute. Hence the distinction between relative and absolute paths is done automatically. There also will be a runtime warning when the executable can't be found at `RTTR_BINDIR` after changing the work dir. The settings directory will still be the home and can't be changed, which is ok IMO. There also is `RTTR_BUILD_UPDATER` which can be used to not build the updater. This is OFF by default when any path is absolute (except for the game dir) and should be set to off when any custom path is used.
I even think we should make a `RTTR_OFFICIAL_BUILD` variable which forces the directories to the defaults (fixed) and enables the updater. However I do not want to force disable the updater build as for test-building/developing it may be helpful even though non-default paths are used.
