### ISSUE TITLE
some bushes in the terrain interfere with pathbuilding

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#750]
These bushes should be ereased when they are in the way of a newly built path, but they're not

![buesche](https://user-images.githubusercontent.com/14232936/32694228-274f1dbc-c73b-11e7-91ec-bd21fe79b438.png)

**Comment by Flamefire** [comment]
Can I get the replay for this please?

**Comment by stefson** [comment]
I started a new game, with the same map and the same spot, because I wasn't sure anymore which replay is the corresponding one and I cannot replay them at the moment. So yeah, could nail it down a bit - there are various tiny objects on the map, such as tree stubs and little rocks, none of them are ereased when you built a path on top of them. And this is either the original behavior, or this happens for so long in s25rttr that I forgot about how it used to be before, haha :) however, with these a bit bigger bushes it clearly popps into one's eye and should be avoided, if possible. All these objects vanish if you built a flag post on top of them, the marked bushes as well, but in the screenshot I provided they were too closed to the building for that. 

[replay and saves.zip](https://github.com/Return-To-The-Roots/s25client/files/1464707/replay.and.saves.zip)

**Comment by Flamefire** [comment]
The problem is that we have an incomplete list of environment objects that should be removed when a road is build. 

IMO there are only 2 types of environment objects: Ones that block a road building and ones that don't. The latter should get removed when a road is build so there will **never** be an environment object on a road.

Question: Is this wrong? aka: Are there any environment objects that should stay even when there is a road?

**Comment by Spikeone** [comment]
Yes there are some - I thought the shown object was one of those - but it's not, guess a list would help. But regarding all those special objects...

**Comment by Flamefire** [comment]
However currently we decide this based on the texture (image). It should be a proper property.

I changed this to remove everything now. If you find anything that should not be removed but does also not disallow building a road, tell me. But IMO there has to be a good reason because in real world when you construct a road you remove everything in its path
