### ISSUE TITLE
Disable Notification for Water if exhaustible wells is disabled

### ISSUE THREAD

**Issue by Shawn8901** [Return-To-The-Roots/s25client#754]
While playing some rounds rttr in multiplayer, we always have exhaustible wells disabled.
If you send a geologist and he found water, a notification is send.
we regognized that there is water all over the map and if the wells will never exhaust, there is no real reason to send a notification to the player.

I have checked the map editor and there is no way to set water as resource, so i assume that all resource piles are filled with water.

So it would be nice to disable the notification, if wells will not exhaust.

**Comment by Flamefire** [comment]
This is true but not completely. In the current(!) map editor it is not possible to set water. However water is a resource as any other and present in the map file. On loading we perform some validation: If there is water but the terrain is e.g. dessert, we remove it. But we don't add water and not everywhere is water, although be convention there should.
Also: The found message is only shown once per geologist and only if there is no other water sign around.

So bottom line: Finding water is useful to be sure there is water. You can assume water on suitable terrain but there might be none. And lastly: Isn't it part of the original S2 feeling getting a message from a geologist and then be disappointed because he only found water?

Hence: I would not fix that. And if we would, I'd rather make 3 settings for the wells: Original, Water everywhere (no messages), Exhaustible. Because if you don't force water everywhere you need the messages.

**Comment by Spikeone** [comment]
I agree with @Flamefire that this is something the original game had and current maps have water at those spots. Also it is possible to remove water, actually this inspired me to create a desert with oasis like map and remove the water resource.

But, I'd also say we should have client side addons, which could include setting that is called "disable water notifications when wells are inexhaustible"

So players like me still have the original feeling of beeing disappointed by a geologist who first finds water while other players do not care at all

**Comment by Flamefire** [comment]
Hm, we don't have client-side addons ATM. I'm reluctant to add them due to the complexity this might introduce.
And for a global addon this won't be useful if we don't also set the water everywhere (see my reply)

**Comment by Shawn8901** [comment]
i for my own never noticed any place on a map where a well does not find any water, so its nice to know that it could happen.
I think a 3-way addon (like Flamefire mentioned) is okay for me. 
if the option "water everywhere" is enabled, would you prefere that a geologist will find water in every case, or that a well will "find" water?

**Comment by Flamefire** [comment]
Yeah most maps simply have water everywhere.

Both. I would simply place water on all terrain that can have water (so no dessert) which the geologist and well will find. But I would also disable the message as in your patch

**Comment by Shawn8901** [comment]
I have now Changed AddonExhaustibleWells to an AddonList and added an option for disabled and no water notification.
if i understand you right, the game places water everywhere (except desert and so on), so i think there are no further changes required.

**Comment by Spikeone** [comment]
What about letting geologists simply not search on ground in an addon? This would also increase searching speed so a good idea for an addon maybe?

**Comment by Flamefire** [comment]
Nope, the game does not place any water. That would have to be done manually, e.g. in the loading process. Look for the place where it changes the water depending on the terrain.

I would use options: "Inexhaustible (default)", "Inexhaustible and water everywhere", "Exhaustible" and change the name and description

**Comment by Shawn8901** [comment]
For me just to understand it right:
Everywhere including or excluding desert?

**Comment by Flamefire** [comment]
I'd exclude it. Maybe you have a better name for the option?
Check https://github.com/Return-To-The-Roots/s25client/blob/86a77576d5d7d16d49df75a29f3ad35f6ad70544/src/world/MapLoader.cpp#L117 for the implementation

**Comment by Shawn8901** [comment]
Are there any other things left, which i may improve?

**Comment by Flamefire** [comment]
Could you open a PR? It is easier to comment there
