### ISSUE TITLE
lava texture flickers 

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#765]
I'm about to test the random map feature a bit, and so generated myself a wintermap with a few vulcanos :) unfortunatley these do flicker a lot, and pretty fast, eye tearing fast. Took me a while to have a screenshot with both phases, here it is: 

![0001](https://user-images.githubusercontent.com/14232936/33242091-99989a48-d2cf-11e7-8892-d675c5875d39.png)
![0002](https://user-images.githubusercontent.com/14232936/33242105-ec94b4b6-d2cf-11e7-99bf-ec5ca93fc125.png)

I'm on linux x86_64, toolchain is gcc-6.4.0, glibc-2.25, binutils-2.29.1, and boost 1.63, if this matters.

**Comment by stefson** [comment]
here is the map, since it is a random map and might be of interest? 

[Random.swd.zip](https://github.com/Return-To-The-Roots/s25client/files/1504050/Random.swd.zip)

**Comment by Shawn8901** [comment]
Isnt this the "normal" texture change of lava?

**Comment by Spikeone** [comment]
Well, I can't load the map with the latest available nightly build.

**Comment by stefson** [comment]
Are you at current head 89edd04d7b3d8fbdb8a86b79415489d8c0b713a6 ? Any error in the console? 

(I'm uncertain if this is the original behavior, it is some 20 years ago I played the original Game on a Windows PC)

**Comment by Spikeone** [comment]
20170924	1903c0f

As said latest nightly build. Game just keeps loading and is not responding. Also the map preview is not working. I copied the map and when selecting that copy the game stops working when hitting continue.

**Comment by stefson** [comment]
Thats two months ago, isn't it? You should give that build server a firm kick :) 

For the texture: I think it was sort of wobbering, giving the illusion of floating around in that, but no flicker whatsoever - these two textures flipp at least 5 times per second.

Will reinstall the old 0.8.1 stable to check/confirm.

**Comment by Spikeone** [comment]
It is only one texture which uses palette rotation, guess there should be 4 steps instead of 2, but maybe they are just fast.

**Comment by Shawn8901** [comment]
I have checked the implementation for the current head.
Lava contains of 4 frames, all of them should be displayed for about 780ms.
The animation length is calculated in GameClient::GetGlobalAnimation and is called by TerrainRenderer::Draw.
For a less annoying flickering it  would be possible to increase the factor_numerator to 8-10 switch results to a display of 1,2-1,5s.
Other good option would be to change the animation to 1-2-3-4-3-2-1-2 and so on, if possible.
I think i would prefer the second choice.

**Comment by Flamefire** [comment]
I don't understand what you mean with "which is not intended by the function". It is a parameter to the function so you can freely change the numerator and denominator. However this is the wrong place. The lava looks wrong because it IS wrong:
![lava](https://user-images.githubusercontent.com/309017/33292435-8749aefe-d3c9-11e7-9360-3fd9731ba088.png)

We have to check the texture extraction code for the bug.

**Comment by Flamefire** [comment]
@Spikeone Thanks for mentioning this bug. The problem is that the map is invalid for the old implementation which is detected but never properly handled.

**Comment by Flamefire** [comment]
Update to the post above: Left is the new editor not the original one. The new one uses movement instead of color animation which looks entirely different. The original is finer, like the right picture but still w/o flickering.

Found the cause: The texture uses a palette animation. But we load the images unpaletted. If the palette colors were unique than that translation is ok. However there are duplicate colors in that palette which cause one color to be preferred ingame and destroys the whole animation. Hence we need to load the file in the original format.
