### ISSUE TITLE
Savannah uses wrong edge

### ISSUE THREAD

**Issue by Spikeone** [Return-To-The-Roots/s25client#788]
Currently sandy edge is used, should be meadow

![image](https://user-images.githubusercontent.com/1276342/34360517-ce37be60-ea61-11e7-90f9-367cee770b8e.png)

**Comment by Flamefire** [comment]
It's a feature. The original is wrong as it does not hide the triangle shape

**Comment by Spikeone** [comment]
That might be correct but it's still looking odd as there is more green in savannah than... sandy color which results in a strange edge rather than a flawless edge - so I can't agree that it's a feature :-/

**Comment by Flamefire** [comment]
I find the edge in the lower image way more visible than the one in the top. The hard cut on the bright background is clearly visible. The cut of the grass on top is less.

In the end I think this whole edge thing is flawed. If you check the texture images they are bended the wrong way and we need to do some trickery to get them right (just noticed that when fixing the editor that you can't just blit(copy) the image) I checked widelands and they use a mask applied to the terrain texture. That gives a very nice edge as the same terrain is used and avoids all these "which edge is used for what" guessing.

**Comment by Spikeone** [comment]
Overall I totally agree with you - also a savannah (grass + sand) -> sand -> Water order is just logic. 

I also agree that there are ways which could be even better - yet, it's not like the original then. Would still like to add more options just for such things as OTTD does, they have tons of options so everybody can just pick what he/she likes at all but as far as I remember you are not a fan of client side options.

I will check some maps, if that savannah edge makes things worse or better and comment again. Guess thats the best way at all

**Comment by Flamefire** [comment]
The problem with options is maintenance: Every On/Off option **doubles** the possibilities: 2 options: Off+Off, Off+On, On+Off, On+On -> 4 things to test.
And we have to implement all the switching, GUI elements, saving/loading etc. instead of simply saying: We use this edge as a compromise.

Mockup (with my epic paint skills) how the edge mask approach would look like. Look at the top and right and compare with your screenshots. IMO although it is not the same as the original, I think it is more like it was meant to be. If they could have they would have done it the same, I guess. And we still use the same graphics only slightly improve them and make life easier for us.
![unbenannt](https://user-images.githubusercontent.com/309017/34378666-52a40d8a-eaf7-11e7-9733-7619cde6de7a.png)
