### ISSUE TITLE
Consider moving RTTR_BINDIR/RTTR binaries to RTTR_DATADIR

### ISSUE THREAD

**Issue by ibara** [Return-To-The-Roots/s25client#791]
Hi --

I've created a package of rttr for OpenBSD and I am about to import it into our official package repository. There was a concern brought up during the package creation process from other developers: that two binaries (s-c_resample and sound-convert) are placed into RTTR_BINDIR/RTTR (aka /usr/local/bin/RTTR on OpenBSD), which is a subdirectory of the usual package binary directory. It was observed that in nearly 10,000 packages in the OpenBSD package repository, none of them do this. In our experience, binaries that are not reachable from a default path would be put in something like share/s25rttr (CorsixTH does this, for example: the binary is installed as /usr/local/share/CorsixTH/CorsixTH and then reached through a wrapper script).

I would be wondering if you would consider moving s-c_resample and sound-convert to the share/s25rttr directory. This would make packaging easier for more than just OpenBSD, I believe.

Thanks!

**Comment by Flow86** [comment]
Hi,
it was in share/s25rttr, but someone didnt like that (I think gentoo had a different approach and does not want the binaries in share?)

I'm not sure at the moment, but I think you could override that path via cmake? (if not, we should add an option for it)

**Comment by Flamefire** [comment]
According to https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html the `bin` dir is the correct path for executable binaries and `share` is `read-only architecture-independent data`. So I don't think it belongs there. Honestly I don't know enough about the lfs file system to make a good decision where to place stuff (this is why I followed the description from cmake) maybe @hasufell might have an idea?

Point was: We place the main binaries (s25client, s25edit) into bin. The updater and sound converter are only required once in a while (converter only once in most cases). I would place the updater into bin directly as it won't cause any naming problems (s25update). The converter though has a quite generic name which is why we wanted to have it separately.

**Question:** Would it be acceptable to place the sound converter binaries into RTTR_BINDIR directly? Or do we really need an extra dir for that? Or is there even a "correct" path where to put supplementary binaries?

**Comment by ibara** [comment]
From an OpenBSD packaging perspective, I'd be perfectly happy placing those binaries directly into RTTR_BINDIR (you're right, maybe with a more unique name).

The concern was that we were installing unreachable binaries from a package, since RTTR_BINDIR will be part of a user's default PATH, but RTTR_BINDIR/RTTR is not. The concern was further magnified on the off-change you all started calling those supplimental binaries from a relative path from system() since the directories in PATH are not searched recursively.

**Comment by Flamefire** [comment]
IMO that is ok. With the new `RttrConfig` we are able to determine the absolute path of RTTR_BINDIR at runtime and hence also the binary. So there are no more relative paths used and everything should work fine. If that is the only concern I'd suggest you verify that it works for your setup and we keep it as-is.

Otherwise I would rename sound_convert to s25soundConvert but keep the name of the resampling binary as it is pretty generic. But I'm open to other opinions.

**Comment by ibara** [comment]
OpenBSD has no support for discovering the absolute path of a running binary, so it is patched out of our package.

**Comment by Flamefire** [comment]
Oh really? That is new to me as there is a branch for BSD systems.
However if the RTTR_BINDIR is set to an absolute path it is used for the binaries. Even if it is set to e.g. `bin` and the CMAKE_INSTALL_PREFIX is set to `/usr/local` then it will work too. So we are using the compile time defines for figuring out the path to the files.

**Comment by ibara** [comment]
You can't treat the BSDs like you'd treat Linux. That branch works perfectly fine on FreeBSD, for example, which does have the ability to get the path of a running binary.

**Comment by hasufell** [comment]
`/usr/share` is wrong for binaries. It's for **architecture independent** data: http://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html#usrshareArchitectureindependentData

Throwing binaries in there will even break multi-arch on various distros.

**Comment by Flow86** [comment]
> Otherwise I would rename sound_convert to s25soundConvert but keep the name of the resampling binary as it is pretty generic. But I'm open to other opinions.

Perhaps with some kind of prefix?

s25rttr-sound-convert
s25rttr-s-c-resample

?

**Comment by Flamefire** [comment]
@ibara Could you show me your patch? Then I could include it in the main repo.

And still: If rttr is configured correctly everything would work as-is and we can still use the directory instead of the prefix. If the directory is really disliked (just for the style reason, functionally it is completely ok! @hasufell what do you say?) then we prefix the binaries.
@Flow86 I'd stay with the s25 prefix. s25rttr- seems so verbose. But doesn't matter.

**Comment by ibara** [comment]
The directory is really disliked. We do not want to put binaries any subdirectory of the user's default PATH, since they're unreachable.

@flamefire Sure, but, patch for what?

**Comment by Flamefire** [comment]
What I don't understand is : why should it be reachable? Rttr can use it and the binaries are not of much use for others.

This patch: `OpenBSD has no support for discovering the absolute path of a running binary, so it is patched out of our package`

**Comment by hasufell** [comment]
What's wrong with `/usr/libexec`? See FHS: http://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s07.html

> usr/libexec includes internal binaries that are not intended to be executed directly by users or shell scripts. Applications may use a single subdirectory under /usr/libexec.

**Comment by Flamefire** [comment]
Sounds resonable. It is also supported by [GNUInstallDirs](https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html).
In the linked [GNU site](http://www.gnu.org/prep/standards/html_node/Directory-Variables.html) it is stated as

> The definition of ‘libexecdir’ is the same for all packages, so you should install your data in a subdirectory thereof. Most packages install their data under $(libexecdir)/package-name/, possibly within additional subdirectories thereof, such as $(libexecdir)/package-name/machine/version. 

However I would simply add a `RTTR_EXTRA_BINARIES` defaulting to `CMAKE_LIBEXEC_DIR/RTTR`. Everyone happy with that?

**Comment by ibara** [comment]
Yes

**Comment by stefson** [comment]
With the changes applied, where does the build script except the data files to be found? Right now it seems to be /share/s25rttr/S2 , at least this is working for me with my own very hackish gentoo ebuild, set via 
```
	local mycmakeargs=(
		-DRTTR_GAMEDIR"share/s25rttr/S2/"
```

in src prepare.

**Comment by Flamefire** [comment]
That is unaffected. The game data will stay in `RTTR_GAMEDIR` which defaults to `"${CMAKE_INSTALL_DATAROOTDIR}/s25rttr/S2"`

**Comment by ibara** [comment]
Thank you. Much appreciated!

**Comment by Flow86** [comment]
default libexecdir should be .../s25rttr (package-name) instead of .../RTTR

**Comment by Flamefire** [comment]
true. Will be done
