### ISSUE TITLE
soldiers are randoomly sent to and pulled from towers in an endless loop

### ISSUE THREAD

**Issue by stefson** [Return-To-The-Roots/s25client#871]
It starts at ~74.000 GF,  happens with the tower at position 75:64 , but also with the one at 74:71
[2018-09-07_10-39-15.rpl.zip](https://github.com/Return-To-The-Roots/s25client/files/2360456/2018-09-07_10-39-15.rpl.zip)

There is one enemy south of that position, but that can't really explain the ongoing fluctuation of the soldiers, can it?

**Comment by Flamefire** [comment]
Found the problem: It is caused by a bug treating not-yet-occupied military buildings differently when checking for "close-to-borderness" from either side.

I assume in the original an existing military building close to a built, but not yet occupied enemy building is considered border (as in: border status changes as soon as the building is finished).

Is this correct?

**Comment by stefson** [comment]
It is likely that you're right with your first statement (can't say for sure though), but I don't really understand the second statement?

**Comment by Flamefire** [comment]
Situation: You have a military building that is occupied with soldiers close to the enemy border but not very close to any enemy military building so that it counts as "mid range" (1 line on the flag)

1. Now the enemy starts building a new military building closer to yours
2. The construction is finished
3. the enemies soldiers get into that building

Now your building counts as "border" (cross on white flag).

I assume this change form "mid" to "border" occurs at step 2 in the original.

**Comment by stefson** [comment]
I could reproduce it: jump to frame ~73.000 and position 129:135 

[2018-09-23_08-54-11.rpl.zip](https://github.com/Return-To-The-Roots/s25client/files/2408525/2018-09-23_08-54-11.rpl.zip)
